"""Google upsert endpoint — called by the Next.js NextAuth signIn callback.

The Next.js frontend handles all Google OAuth interactions via NextAuth.
When a user first signs in, NextAuth's server-side signIn callback POSTs
the verified email + name here.  We find-or-create the users row and
return the UUID so NextAuth can embed it in the session JWT.

This endpoint is gated by INTERNAL_API_KEY (server-to-server only).
It is never called from the browser.
"""

import uuid
from datetime import UTC, datetime
from typing import Literal

import structlog
from fastapi import APIRouter, Depends, HTTPException, Request, status
from pydantic import BaseModel, EmailStr
from sqlalchemy import func, select, update
from sqlalchemy.ext.asyncio import AsyncSession

from app.auth import _verify_internal_key, get_current_user
from app.config import settings
from app.database import get_db
from app.models import MobileIdentity, MobileSession, User
from app.services.mobile_auth import (
    MobileAuthError,
    decode_access_token,
    issue_access_token,
    new_refresh_token,
    refresh_expiry,
    refresh_token_hash,
    verify_provider_id_token,
)

log = structlog.get_logger(__name__)
router = APIRouter()


def _auth_email_lock_key(email: str) -> str:
    return f"native-auth:email:{email.lower()}"


def _auth_identity_lock_key(provider: str, subject: str) -> str:
    return f"native-auth:identity:{provider}:{subject}"


async def _acquire_auth_locks(db: AsyncSession, *keys: str) -> None:
    """Serialize auth decisions whose unique rows may not exist yet.

    Row locks cannot protect an absent identity or user. PostgreSQL advisory
    transaction locks cover that gap and are released automatically on commit
    or rollback. Sorting is required when a request takes both locks so two
    requests cannot deadlock by acquiring the same keys in a different order.
    """
    for key in sorted(set(keys)):
        await db.execute(select(func.pg_advisory_xact_lock(func.hashtextextended(key, 0))))


class GoogleUpsertRequest(BaseModel):
    email: EmailStr
    name: str | None = None


class GoogleUpsertResponse(BaseModel):
    user_id: str
    created: bool


def _require_internal_key(request: Request) -> None:
    # Single source of truth for the fail-closed rule (see app.auth):
    # an unset server key rejects rather than bypassing.
    _verify_internal_key(request.headers.get("authorization"))


@router.post("/google-upsert", response_model=GoogleUpsertResponse)
async def google_upsert(
    body: GoogleUpsertRequest,
    request: Request,
    db: AsyncSession = Depends(get_db),
) -> GoogleUpsertResponse:
    _require_internal_key(request)

    await _acquire_auth_locks(db, _auth_email_lock_key(str(body.email)))
    result = await db.execute(select(User).where(func.lower(User.email) == str(body.email).lower()))
    user = result.scalar_one_or_none()

    if user is not None:
        log.info("auth.google_upsert.existing", user_id=str(user.id), email=body.email)
        return GoogleUpsertResponse(user_id=str(user.id), created=False)

    user = User(
        id=uuid.uuid4(),
        email=body.email,
        name=body.name,
        auth_provider="google",
        onboarding_status="pending",
    )
    db.add(user)
    await db.commit()
    await db.refresh(user)
    log.info("auth.google_upsert.created", user_id=str(user.id), email=body.email)
    return GoogleUpsertResponse(user_id=str(user.id), created=True)


# ── Native mobile auth ───────────────────────────────────────────────────────


class MobileExchangeRequest(BaseModel):
    provider: Literal["google", "apple"]
    id_token: str
    # The nonce is generated by the native client and must be echoed by the
    # provider token.  It is never accepted from an unverified user profile.
    nonce: str


class MobileUserOut(BaseModel):
    id: str
    email: EmailStr
    name: str | None = None
    onboarding_status: str
    linked_providers: list[Literal["google", "apple"]] = []


class MobileSessionOut(BaseModel):
    access_token: str
    refresh_token: str
    token_type: Literal["Bearer"] = "Bearer"
    expires_in: int
    user: MobileUserOut


class MobileRefreshRequest(BaseModel):
    refresh_token: str


class MobileRevokeResponse(BaseModel):
    revoked: bool = True


class MobileLinkResponse(BaseModel):
    linked: bool = True
    linked_providers: list[Literal["google", "apple"]] = []


def _mobile_user(user: User, providers: list[str] | None = None) -> MobileUserOut:
    return MobileUserOut(
        id=str(user.id),
        email=user.email,
        name=user.name,
        onboarding_status=user.onboarding_status,
        linked_providers=[
            provider for provider in (providers or []) if provider in {"google", "apple"}
        ],
    )


async def _issue_mobile_session(
    user: User,
    provider: str,
    db: AsyncSession,
    *,
    family_id: uuid.UUID | None = None,
) -> MobileSessionOut:
    raw_refresh = new_refresh_token()
    session = MobileSession(
        user_id=user.id,
        token_hash=refresh_token_hash(raw_refresh),
        family_id=family_id or uuid.uuid4(),
        provider=provider,
        token_version=1,
        expires_at=refresh_expiry(),
    )
    db.add(session)
    await db.flush()
    access, expires_in = issue_access_token(user.id, session.id, session.token_version)
    return MobileSessionOut(
        access_token=access,
        refresh_token=raw_refresh,
        expires_in=expires_in,
        user=_mobile_user(user),
    )


def _mobile_error(
    error: MobileAuthError, code: int = status.HTTP_401_UNAUTHORIZED
) -> HTTPException:
    return HTTPException(status_code=code, detail={"code": error.code, "message": error.message})


@router.post("/mobile/exchange", response_model=MobileSessionOut)
async def mobile_exchange(
    body: MobileExchangeRequest, db: AsyncSession = Depends(get_db)
) -> MobileSessionOut:
    """Exchange a verified Google/Apple ID token for a native session.

    Linking is intentionally provider-specific.  A verified Google token may
    migrate a pre-mobile legacy Google account with the same normalized email;
    Apple is never linked by email because private-relay addresses are not a
    safe proof of control of an existing account.  A future authenticated link
    flow can add an identity explicitly.
    """
    if not settings.mobile_jwt_secret:
        raise HTTPException(status_code=503, detail="Mobile authentication is not configured")
    try:
        claims = await verify_provider_id_token(body.id_token, body.provider, body.nonce)
    except MobileAuthError as exc:
        raise _mobile_error(exc) from exc

    await _acquire_auth_locks(
        db,
        _auth_email_lock_key(claims.email),
        _auth_identity_lock_key(claims.provider, claims.subject),
    )
    identity = (
        await db.execute(
            select(MobileIdentity).where(
                MobileIdentity.provider == claims.provider,
                MobileIdentity.subject == claims.subject,
            )
        )
    ).scalar_one_or_none()
    if identity is not None:
        user = (
            await db.execute(select(User).where(User.id == identity.user_id))
        ).scalar_one_or_none()
        if user is None:
            raise HTTPException(status_code=401, detail="User not found")
        identity.last_seen_at = datetime.now(UTC)
    else:
        user = (
            await db.execute(select(User).where(func.lower(User.email) == claims.email.lower()))
        ).scalar_one_or_none()
        if user is not None:
            if claims.provider != "google" or user.auth_provider != "google":
                raise HTTPException(
                    status_code=status.HTTP_409_CONFLICT,
                    detail={
                        "code": "provider_link_required",
                        "message": (
                            "Sign in with the existing provider or explicitly link "
                            "this provider first"
                        ),
                    },
                )
            # Safe, one-way migration of the existing NextAuth Google account.
        else:
            user = User(
                id=uuid.uuid4(),
                email=claims.email,
                name=claims.name,
                auth_provider=claims.provider,
                onboarding_status="pending",
            )
            db.add(user)
            await db.flush()
        db.add(
            MobileIdentity(
                user_id=user.id,
                provider=claims.provider,
                subject=claims.subject,
                issuer=claims.issuer,
                email=claims.email,
                email_verified=True,
            )
        )
    if claims.name and not user.name:
        user.name = claims.name
    result = await _issue_mobile_session(user, claims.provider, db)
    providers = (
        (await db.execute(select(MobileIdentity.provider).where(MobileIdentity.user_id == user.id)))
        .scalars()
        .all()
    )
    result.user = _mobile_user(user, list(providers))
    await db.commit()
    return result


@router.post("/mobile/refresh", response_model=MobileSessionOut)
async def mobile_refresh(
    body: MobileRefreshRequest, db: AsyncSession = Depends(get_db)
) -> MobileSessionOut:
    if not body.refresh_token or not settings.mobile_jwt_secret:
        raise HTTPException(status_code=401, detail="Invalid refresh token")
    token_hash = refresh_token_hash(body.refresh_token)
    session = (
        await db.execute(
            select(MobileSession).where(MobileSession.token_hash == token_hash).with_for_update()
        )
    ).scalar_one_or_none()
    if session is None:
        raise HTTPException(status_code=401, detail="Invalid refresh token")
    now = datetime.now(UTC)
    if session.used_at is not None:
        # Reuse of any rotated token invalidates the complete family.  This is
        # the critical replay boundary; do not merely reject this one token.
        await db.execute(
            update(MobileSession)
            .where(MobileSession.family_id == session.family_id)
            .values(revoked_at=now)
        )
        await db.commit()
        raise HTTPException(status_code=401, detail={"code": "refresh_reuse_detected"})
    session_expiry = session.expires_at
    if session_expiry.tzinfo is None:
        session_expiry = session_expiry.replace(tzinfo=UTC)
    if session.revoked_at is not None or session_expiry <= now:
        raise HTTPException(status_code=401, detail="Invalid refresh token")
    user = (await db.execute(select(User).where(User.id == session.user_id))).scalar_one_or_none()
    if user is None:
        raise HTTPException(status_code=401, detail="User not found")
    session.used_at = now
    session.last_used_at = now
    result = await _issue_mobile_session(user, session.provider, db, family_id=session.family_id)
    # The replacement relation is written after flush, when the new session id
    # is available, and before commit so both operations are atomic.
    replacement = (
        await db.execute(
            select(MobileSession).where(
                MobileSession.token_hash == refresh_token_hash(result.refresh_token)
            )
        )
    ).scalar_one()
    session.replaced_by = replacement.id
    providers = (
        (await db.execute(select(MobileIdentity.provider).where(MobileIdentity.user_id == user.id)))
        .scalars()
        .all()
    )
    result.user = _mobile_user(user, list(providers))
    await db.commit()
    return result


@router.post("/mobile/link", response_model=MobileLinkResponse)
async def mobile_link(
    body: MobileExchangeRequest,
    request: Request,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> MobileLinkResponse:
    """Explicitly link a second provider after recent authenticated access."""
    authorization = request.headers.get("authorization", "")
    if not authorization.startswith("Bearer ") or not settings.mobile_jwt_secret:
        raise HTTPException(status_code=401, detail="Recent mobile authentication required")
    try:
        access = decode_access_token(authorization[7:])
    except MobileAuthError as exc:
        raise _mobile_error(exc) from exc
    now = int(datetime.now(UTC).timestamp())
    if (
        access.user_id != current_user.id
        or now - access.issued_at > settings.mobile_link_max_auth_age_seconds
    ):
        raise HTTPException(status_code=401, detail="Recent mobile authentication required")
    try:
        claims = await verify_provider_id_token(body.id_token, body.provider, body.nonce)
    except MobileAuthError as exc:
        raise _mobile_error(exc) from exc
    await _acquire_auth_locks(
        db,
        _auth_email_lock_key(claims.email),
        _auth_identity_lock_key(claims.provider, claims.subject),
    )
    identity = (
        await db.execute(
            select(MobileIdentity).where(
                MobileIdentity.provider == claims.provider,
                MobileIdentity.subject == claims.subject,
            )
        )
    ).scalar_one_or_none()
    if identity is not None:
        if identity.user_id != current_user.id:
            raise HTTPException(status_code=409, detail={"code": "provider_already_linked"})
        # The provider subject is the canonical identity. A replay by its owner
        # remains idempotent even if the provider has since changed the email
        # claim to an address that belongs to another Nova account.
        identity.last_seen_at = datetime.now(UTC)
    else:
        existing_user = (
            await db.execute(select(User).where(func.lower(User.email) == claims.email.lower()))
        ).scalar_one_or_none()
        if existing_user is not None and existing_user.id != current_user.id:
            raise HTTPException(status_code=409, detail={"code": "provider_link_email_conflict"})
        db.add(
            MobileIdentity(
                user_id=current_user.id,
                provider=claims.provider,
                subject=claims.subject,
                issuer=claims.issuer,
                email=claims.email,
                email_verified=True,
            )
        )
    await db.commit()
    providers = (
        (
            await db.execute(
                select(MobileIdentity.provider).where(MobileIdentity.user_id == current_user.id)
            )
        )
        .scalars()
        .all()
    )
    return MobileLinkResponse(linked_providers=list(providers))


@router.post("/mobile/revoke", response_model=MobileRevokeResponse)
async def mobile_revoke(
    body: MobileRefreshRequest, db: AsyncSession = Depends(get_db)
) -> MobileRevokeResponse:
    if body.refresh_token and settings.mobile_jwt_secret:
        session = (
            await db.execute(
                select(MobileSession).where(
                    MobileSession.token_hash == refresh_token_hash(body.refresh_token)
                )
            )
        ).scalar_one_or_none()
        if session is not None:
            await db.execute(
                update(MobileSession)
                .where(MobileSession.family_id == session.family_id)
                .values(revoked_at=datetime.now(UTC))
            )
            await db.commit()
    return MobileRevokeResponse()


@router.get("/mobile/me", response_model=MobileUserOut)
async def mobile_me(
    current_user: User = Depends(get_current_user), db: AsyncSession = Depends(get_db)
) -> MobileUserOut:
    # The identity list is queried explicitly to avoid ORM lazy-loads in an
    # async request and to make tenant scoping obvious.
    providers = (
        (
            await db.execute(
                select(MobileIdentity.provider).where(MobileIdentity.user_id == current_user.id)
            )
        )
        .scalars()
        .all()
    )
    return _mobile_user(current_user, list(providers))
