"use client";

/**
 * FontAlternatives — admin tile picker for CLIP-identified font candidates.
 *
 * Renders the top-N visually-similar registry fonts (populated by the PR2
 * font-identification pipeline) as click-to-swap tiles. Previews are
 * precomputed PNGs under /font-previews/<family-slug>.png, generated by
 * scripts/generate_font_embeddings.py so the browser doesn't need every
 * registry font as CSS.
 *
 * Hosted alongside the existing FontPicker dropdown in PropertyPanel — the
 * dropdown is still the canonical "pick anything" surface, this is the
 * "pick from the matcher's top suggestions" shortcut.
 */
import type { Dispatch } from "react";
import type { EditorAction, RecipeTextOverlay } from "./recipe-types";

function slugify(family: string): string {
  return family.toLowerCase().replace(/\s+/g, "-");
}

interface FontAlternativesProps {
  overlay: RecipeTextOverlay;
  slotIndex: number;
  overlayIndex: number;
  dispatch: Dispatch<EditorAction>;
}

export function FontAlternatives({
  overlay,
  slotIndex,
  overlayIndex,
  dispatch,
}: FontAlternativesProps) {
  const alternatives = overlay.font_alternatives;

  // Pipeline didn't run on this overlay (no text_bbox, or matcher failed
  // best-effort). Don't render the section — fall back to the regular
  // FontPicker dropdown which is always visible above this.
  if (!alternatives || alternatives.length === 0) {
    return null;
  }

  const currentFamily = overlay.font_family;

  const applyToThisOverlay = (family: string) => {
    dispatch({
      type: "UPDATE_OVERLAY_FIELD",
      slotIndex,
      overlayIndex,
      field: "font_family",
      value: family,
    });
  };

  const applyToAll = (family: string) => {
    dispatch({ type: "APPLY_FONT_TO_ALL_OVERLAYS", family });
  };

  return (
    <div className="space-y-2 pt-1">
      <div className="flex items-center justify-between">
        <label className="text-xs text-zinc-400">
          Suggested fonts ({alternatives.length})
        </label>
        <span className="text-[10px] text-zinc-600">
          click to apply · top match: {(alternatives[0].similarity * 100).toFixed(0)}%
        </span>
      </div>
      <div className="grid grid-cols-4 gap-2">
        {alternatives.map((alt) => {
          const isCurrent = alt.family === currentFamily;
          return (
            <button
              key={alt.family}
              type="button"
              onClick={() => applyToThisOverlay(alt.family)}
              className={[
                "group relative flex flex-col items-center gap-1 rounded border p-1 transition",
                isCurrent
                  ? "border-emerald-500 bg-emerald-950/30"
                  : "border-zinc-800 bg-zinc-950 hover:border-zinc-600",
              ].join(" ")}
              title={`${alt.family} — ${(alt.similarity * 100).toFixed(1)}% similar`}
            >
              {/*
                Plain <img> on purpose: these are small precomputed static
                PNGs served from /public, no remote loader or responsive
                sizes are needed, so next/image's overhead has no payoff.
              */}
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={`/font-previews/${slugify(alt.family)}.png`}
                alt={alt.family}
                width={120}
                height={40}
                loading="lazy"
                className="h-10 w-full rounded bg-white object-contain"
                onError={(e) => {
                  // Preview missing (registry changed but PNG not regenerated).
                  // Fall back to the family name in default sans-serif so the
                  // tile is still usable rather than showing a broken image.
                  const img = e.currentTarget;
                  img.style.display = "none";
                  const fallback = img.nextElementSibling as HTMLElement | null;
                  if (fallback) fallback.style.display = "flex";
                }}
              />
              <span
                style={{ display: "none" }}
                className="h-10 w-full items-center justify-center rounded bg-zinc-100 text-[10px] text-zinc-900"
              >
                {alt.family}
              </span>
              <span className="w-full truncate text-[10px] text-zinc-300">
                {alt.family}
              </span>
              <span className="text-[9px] text-zinc-500">
                {(alt.similarity * 100).toFixed(0)}%
              </span>
            </button>
          );
        })}
      </div>
      <div className="flex justify-end">
        <button
          type="button"
          onClick={() => applyToAll(alternatives[0].family)}
          className="text-[11px] text-zinc-400 hover:text-zinc-200 underline-offset-2 hover:underline"
          title={`Set every overlay's font_family to ${alternatives[0].family}`}
        >
          Apply &ldquo;{alternatives[0].family}&rdquo; to all overlays →
        </button>
      </div>
    </div>
  );
}
