/**
 * A byte-for-byte port of CPython's `random.Random` (Mersenne Twister
 * MT19937 + CPython's specific integer-seed keying and `genrand_res53`
 * float generation) — NOT a generic MT19937 implementation.
 * Derived from CPython's Modules/_randommodule.c (PSF License 2.0,
 * https://docs.python.org/3/license.html); MT19937 core by
 * Matsumoto & Nishimura (BSD). Needed because
 * `choreography.ts`'s `buildTimeline`/`rollingTimeline` must reproduce the
 * EXACT jitter sequence `app/pipeline/carousel/choreography.py`'s
 * `random.Random(seed).uniform(...)` calls produce, so that
 * `choreography_traces.json` (generated by running the Python builders
 * once and checked in) matches this TS port frame-for-frame — including
 * every hold/pad duration's jittered FRAME COUNT, which is a `round()` of a
 * jittered float and therefore sensitive to the RNG's exact bit stream.
 *
 * Algorithm reference: CPython's `Modules/_randommodule.c`
 * (`init_genrand`, `init_by_array`, `genrand_uint32`, `genrand_res53`) and
 * `random_seed()`'s int-seed key derivation. For `seed=0` specifically (the
 * only seed this package's fixtures use), `random_seed` derives a
 * single-word key `[0]` (n=0 -> bit_length=0 -> keymax=1, and the byte
 * array of `0` is all zero), so `init_by_array([0], 1)` is what actually
 * runs — implemented generically here for any non-negative integer seed.
 */

const N = 624;
const M = 397;
const MATRIX_A = 0x9908b0df;
const UPPER_MASK = 0x80000000;
const LOWER_MASK = 0x7fffffff;

// 32-bit unsigned multiply, matching C's `(uint32_t)(a * b)` wraparound
// semantics — JS's `*` operator loses precision above 2^53, so this must
// use Math.imul-style splitting.
function mulUint32(a: number, b: number): number {
  const aLo = a & 0xffff;
  const aHi = a >>> 16;
  const bLo = b & 0xffff;
  const bHi = b >>> 16;
  const lo = aLo * bLo;
  const mid = ((aLo * bHi + aHi * bLo) & 0xffff) << 16;
  return (lo + mid) >>> 0;
}

export class PythonRandom {
  private readonly mt = new Uint32Array(N);
  private mti = N + 1;

  constructor(seed: number) {
    this.seedFromInt(seed);
  }

  private initGenrand(s: number): void {
    this.mt[0] = s >>> 0;
    for (let i = 1; i < N; i += 1) {
      const prev = this.mt[i - 1] ^ (this.mt[i - 1] >>> 30);
      this.mt[i] = (mulUint32(1812433253, prev) + i) >>> 0;
    }
    this.mti = N;
  }

  private initByArray(initKey: number[]): void {
    this.initGenrand(19650218);
    let i = 1;
    let j = 0;
    let k = Math.max(N, initKey.length);
    for (; k > 0; k -= 1) {
      const prev = this.mt[i - 1] ^ (this.mt[i - 1] >>> 30);
      this.mt[i] = ((this.mt[i] ^ mulUint32(prev, 1664525)) + initKey[j] + j) >>> 0;
      i += 1;
      j += 1;
      if (i >= N) {
        this.mt[0] = this.mt[N - 1];
        i = 1;
      }
      if (j >= initKey.length) j = 0;
    }
    for (k = N - 1; k > 0; k -= 1) {
      const prev = this.mt[i - 1] ^ (this.mt[i - 1] >>> 30);
      this.mt[i] = ((this.mt[i] ^ mulUint32(prev, 1566083941)) - i) >>> 0;
      i += 1;
      if (i >= N) {
        this.mt[0] = this.mt[N - 1];
        i = 1;
      }
    }
    this.mt[0] = 0x80000000;
  }

  /** Mirrors CPython random_seed()'s int-seed key derivation for
   * non-negative `seed` (all this package's fixtures use seed=0). */
  private seedFromInt(seed: number): void {
    if (seed === 0) {
      this.initByArray([0]);
      return;
    }
    let n = Math.floor(Math.abs(seed));
    const key: number[] = [];
    if (n === 0) {
      key.push(0);
    } else {
      while (n > 0) {
        key.push(n % 0x100000000);
        n = Math.floor(n / 0x100000000);
      }
    }
    this.initByArray(key);
  }

  private genrandUint32(): number {
    if (this.mti >= N) {
      const mag01 = [0, MATRIX_A];
      let kk = 0;
      for (; kk < N - M; kk += 1) {
        const y = (this.mt[kk] & UPPER_MASK) | (this.mt[kk + 1] & LOWER_MASK);
        this.mt[kk] = (this.mt[kk + M] ^ (y >>> 1) ^ mag01[y & 0x1]) >>> 0;
      }
      for (; kk < N - 1; kk += 1) {
        const y = (this.mt[kk] & UPPER_MASK) | (this.mt[kk + 1] & LOWER_MASK);
        this.mt[kk] = (this.mt[kk + (M - N)] ^ (y >>> 1) ^ mag01[y & 0x1]) >>> 0;
      }
      const y = (this.mt[N - 1] & UPPER_MASK) | (this.mt[0] & LOWER_MASK);
      this.mt[N - 1] = (this.mt[M - 1] ^ (y >>> 1) ^ mag01[y & 0x1]) >>> 0;
      this.mti = 0;
    }

    let y = this.mt[this.mti];
    this.mti += 1;
    y ^= y >>> 11;
    y = (y ^ ((y << 7) & 0x9d2c5680)) >>> 0;
    y = (y ^ ((y << 15) & 0xefc60000)) >>> 0;
    y ^= y >>> 18;
    return y >>> 0;
  }

  /** Mirrors CPython's `genrand_res53`: a 53-bit-precision float in
   * [0, 1). */
  random(): number {
    const a = this.genrandUint32() >>> 5; // 27 bits
    const b = this.genrandUint32() >>> 6; // 26 bits
    return (a * 67108864.0 + b) / 9007199254740992.0;
  }

  /** Mirrors `random.Random.uniform(a, b)`: `a + (b - a) * random()`. */
  uniform(a: number, b: number): number {
    return a + (b - a) * this.random();
  }
}
