"""Generate or verify the checked Kria runtime-v2 tool contract."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from app.kria.api_schemas import (
    ApprovalDecisionBody,
    ApprovalDecisionOut,
    ApprovalSnapshotOut,
    DraftSnapshotOut,
    DraftUndoBody,
    DraftWriteBody,
    KriaProblemOut,
    SubmitTurnBody,
    ThreadDeltaOut,
    TurnAccepted,
    TurnCancelBody,
    TurnCancelled,
)
from app.kria.contracts import KRIA_SCHEMA_VERSION
from app.kria.registry import KRIA_TOOLS

DEFAULT_SNAPSHOT = Path(__file__).parents[2] / "tests" / "fixtures" / "kria_turns" / "tools.json"
DEFAULT_TYPES = Path(__file__).parents[3] / "web" / "src" / "lib" / "kria-runtime-v2.generated.ts"

API_MODELS = (
    SubmitTurnBody,
    TurnAccepted,
    TurnCancelBody,
    TurnCancelled,
    ApprovalDecisionBody,
    ApprovalDecisionOut,
    ApprovalSnapshotOut,
    DraftSnapshotOut,
    DraftWriteBody,
    DraftUndoBody,
    ThreadDeltaOut,
    KriaProblemOut,
)


def contract_json() -> str:
    payload = {
        "schema_version": KRIA_SCHEMA_VERSION,
        "tools": KRIA_TOOLS.manifest(),
        "api": {model.__name__: model.model_json_schema() for model in API_MODELS},
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def _ts_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return str(schema["$ref"]).rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(_ts_type(value) for value in schema["anyOf"])
    kind = schema.get("type")
    if isinstance(kind, list):
        return " | ".join(_ts_type({"type": value}) for value in kind)
    if kind == "array":
        item = _ts_type(schema.get("items") or {})
        return f"Array<{item}>"
    if kind == "object" or "properties" in schema:
        properties = schema.get("properties") or {}
        if properties:
            required = set(schema.get("required") or [])
            rows = [
                f"{json.dumps(name)}{'' if name in required else '?'}: {_ts_type(value)};"
                for name, value in properties.items()
            ]
            return "{ " + " ".join(rows) + " }"
        additional = schema.get("additionalProperties", True)
        value_type = _ts_type(additional) if isinstance(additional, dict) else "unknown"
        return f"Record<string, {value_type}>"
    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(str(kind), "unknown")


def typescript_contract() -> str:
    """Generate the runtime-v2 browser types from the checked server models."""

    definitions: dict[str, dict[str, Any]] = {}
    roots: list[tuple[str, dict[str, Any]]] = []
    for model in API_MODELS:
        schema = model.model_json_schema()
        definitions.update(schema.pop("$defs", {}))
        roots.append((model.__name__, schema))
    rows = [
        "// Generated by `python -m app.cli.kria_contracts --write`.",
        "// Do not edit by hand; `make verify-kria` checks this file.",
        "",
    ]
    root_names = {name for name, _schema in roots}
    for name in sorted(definitions):
        if name not in root_names:
            rows.append(f"export type {name} = {_ts_type(definitions[name])};")
    for name, schema in roots:
        rows.append(f"export type {name} = {_ts_type(schema)};")
    rows.extend(
        [
            "",
            "export type KriaApprovalSnapshot = ApprovalSnapshotOut;",
            "export type KriaApprovalDecision = ApprovalDecisionOut;",
            "export type KriaTurnAccepted = TurnAccepted;",
            "export type KriaDelta = ThreadDeltaOut;",
            "export type KriaDraftSnapshot = DraftSnapshotOut;",
            "",
        ]
    )
    return "\n".join(rows)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m app.cli.kria_contracts")
    parser.add_argument("--snapshot", type=Path, default=DEFAULT_SNAPSHOT)
    parser.add_argument("--types", type=Path, default=DEFAULT_TYPES)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args(argv)
    rendered = contract_json()
    rendered_types = typescript_contract()
    if args.write:
        args.snapshot.write_text(rendered, encoding="utf-8")
        args.types.write_text(rendered_types, encoding="utf-8")
        print(f"Wrote Kria contract snapshot to {args.snapshot}")
        print(f"Wrote Kria TypeScript contract to {args.types}")
        return 0
    if not args.check:
        print(rendered, end="")
        return 0
    if not args.snapshot.is_file():
        parser.error(f"contract snapshot not found: {args.snapshot}")
    if args.snapshot.read_text(encoding="utf-8") != rendered:
        parser.error(
            "Kria tool contract drifted; review the change and update "
            "tests/fixtures/kria_turns/tools.json"
        )
    if not args.types.is_file():
        parser.error(f"TypeScript contract not found: {args.types}")
    if args.types.read_text(encoding="utf-8") != rendered_types:
        parser.error(
            "Kria TypeScript contract drifted; run python -m app.cli.kria_contracts --write"
        )
    print(f"Kria contract matches {args.snapshot}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
