"""Add plan_items.filming_guide (structured shot list for content-plan items).

Revision ID: 0047
Revises: 0046
Create Date: 2026-06-05

Each plan item now carries a structured filming guide: 2–4 shots, each with
{what, how, duration_s}, generated by the content_plan_generator agent at plan
time. Stored as JSONB so the shape can evolve without further migrations.
NOT NULL + server_default "[]" backfills every existing row to an empty list —
backward-compatible; the frontend falls back to the legacy filming_suggestion line
when the guide is empty.
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0047"
down_revision = "0046"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "plan_items",
        sa.Column(
            "filming_guide",
            postgresql.JSONB(),
            nullable=False,
            server_default="[]",
        ),
    )


def downgrade() -> None:
    op.drop_column("plan_items", "filming_guide")
