#!/usr/bin/env python3
"""Generate admin-only styled font preview PNGs.

These previews are intentionally separate from the CLIP embedding previews
generated by generate_font_embeddings.py. Stroke and shadow make the admin
picker read like short-form video text, but would shift the embedding space.
"""

from __future__ import annotations

import json
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter, ImageFont

CANVAS_SIZE = (600, 120)
TARGET_WIDTH = int(CANVAS_SIZE[0] * 0.8)
MAX_FONT_SIZE = 72
MIN_FONT_SIZE = 18

SCRIPT_DIR = Path(__file__).resolve().parent
API_DIR = SCRIPT_DIR.parent
REPO_ROOT = API_DIR.parents[2]
FONT_DIR = API_DIR / "assets" / "fonts"
REGISTRY_PATH = FONT_DIR / "font-registry.json"
OUTPUT_DIR = REPO_ROOT / "src" / "apps" / "web" / "public" / "font-previews"


def slugify(family: str) -> str:
    return family.lower().replace(" ", "-")


def fit_font(path: Path, text: str) -> ImageFont.FreeTypeFont:
    for size in range(MAX_FONT_SIZE, MIN_FONT_SIZE - 1, -2):
        font = ImageFont.truetype(str(path), size=size)
        bbox = ImageDraw.Draw(Image.new("RGBA", CANVAS_SIZE)).textbbox(
            (0, 0),
            text,
            font=font,
            stroke_width=4,
        )
        if bbox[2] - bbox[0] <= TARGET_WIDTH and bbox[3] - bbox[1] <= 86:
            return font
    return ImageFont.truetype(str(path), size=MIN_FONT_SIZE)


def draw_preview(family: str, font_path: Path, output_path: Path) -> None:
    font = fit_font(font_path, family)
    image = Image.new("RGBA", CANVAS_SIZE, (0, 0, 0, 0))
    draw = ImageDraw.Draw(image)
    bbox = draw.textbbox((0, 0), family, font=font, stroke_width=4)
    text_w = bbox[2] - bbox[0]
    text_h = bbox[3] - bbox[1]
    x = (CANVAS_SIZE[0] - text_w) // 2 - bbox[0]
    y = (CANVAS_SIZE[1] - text_h) // 2 - bbox[1]

    shadow = Image.new("RGBA", CANVAS_SIZE, (0, 0, 0, 0))
    shadow_draw = ImageDraw.Draw(shadow)
    shadow_draw.text(
        (x + 2, y + 4),
        family,
        font=font,
        fill=(0, 0, 0, 128),
        stroke_width=4,
        stroke_fill=(0, 0, 0, 128),
    )
    image.alpha_composite(shadow.filter(ImageFilter.GaussianBlur(radius=2)))

    draw = ImageDraw.Draw(image)
    draw.text(
        (x, y),
        family,
        font=font,
        fill="#FFFFFF",
        stroke_width=4,
        stroke_fill="#000000",
    )
    image.save(output_path)


def main() -> None:
    registry = json.loads(REGISTRY_PATH.read_text())
    active_fonts = {
        family: entry for family, entry in registry["fonts"].items() if not entry.get("deprecated")
    }

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for family, entry in active_fonts.items():
        font_path = FONT_DIR / entry["file"]
        output_path = OUTPUT_DIR / f"{slugify(family)}.png"
        draw_preview(family, font_path, output_path)
        print(output_path)

    print(f"Generated {len(active_fonts)} styled font previews in {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
