"""Generate the native animation DTO from the authoritative Pydantic schema."""

import argparse
import sys
from pathlib import Path

API_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(API_ROOT))

from app.agents._schemas.text_animation_phases import TextAnimationPhases  # noqa: E402
from app.kria.portable_camera import CameraPulse  # noqa: E402

OUTPUT = (
    API_ROOT.parents[2]
    / "src/apps/ios/Packages/KriaMediaEngine/Sources/KriaMediaEngine"
    / "TextAnimationPhases.generated.swift"
)


def generate() -> str:
    properties = TextAnimationPhases.model_json_schema()["properties"]
    assert properties["entrance"]["enum"] == properties["exit"]["enum"]
    edge = ", ".join(properties["entrance"]["enum"])
    loop = ", ".join(properties["loop"]["enum"])
    minimum = properties["speed"]["minimum"]
    maximum = properties["speed"]["maximum"]
    speed = properties["speed"]["default"]
    entrance_default = properties["entrance"]["default"]
    exit_default = properties["exit"]["default"]
    loop_default = properties["loop"]["default"]
    return f"""// Generated by src/apps/api/scripts/generate_native_text_contract.py. Do not edit.
import Foundation

public struct TextAnimationPhases: Codable, Equatable, Sendable {{
    public enum Edge: String, Codable, Sendable {{ case {edge} }}
    public enum Loop: String, Codable, Sendable {{ case {loop} }}
    public var entrance: Edge
    public var exit: Edge
    public var loop: Loop
    public var speed: Double
    public init(entrance: Edge = .{entrance_default}, exit: Edge = .{exit_default},
                loop: Loop = .{loop_default}, speed: Double = {speed}) {{
        self.entrance = entrance; self.exit = exit; self.loop = loop; self.speed = speed
    }}
    private enum CodingKeys: String, CodingKey {{ case entrance, exit, loop, speed }}
    public init(from decoder: Decoder) throws {{
        try rejectUnknownAssetFields(decoder, allowed: ["entrance", "exit", "loop", "speed"])
        let c = try decoder.container(keyedBy: CodingKeys.self)
        entrance = c.contains(.entrance)
            ? try c.decode(Edge.self, forKey: .entrance) : .{entrance_default}
        exit = c.contains(.exit) ? try c.decode(Edge.self, forKey: .exit) : .{exit_default}
        loop = c.contains(.loop) ? try c.decode(Loop.self, forKey: .loop) : .{loop_default}
        speed = c.contains(.speed) ? try c.decode(Double.self, forKey: .speed) : {speed}
        try validate()
    }}
    public func validate() throws {{
        guard speed.isFinite, ({minimum}...{maximum}).contains(speed) else {{
            throw RecipeError.invalidTimeline
        }}
    }}
}}
"""


def generate_camera() -> str:
    properties = CameraPulse.model_json_schema()["properties"]
    id_limit = properties["id"]["maxLength"]
    time_limit = properties["end"]["maximum"]
    intensity_min = properties["intensity"]["minimum"]
    intensity_max = properties["intensity"]["maximum"]
    return rf"""import Foundation

// Generated by src/apps/api/scripts/generate_native_text_contract.py. Do not edit.
public struct CameraPulse: Codable, Equatable, Sendable {{
    public let id: String
    public let start: Double
    public let end: Double
    public let intensity: Double
    public init(id: String, start: Double, end: Double, intensity: Double = 0.04) {{
        self.id = id; self.start = start; self.end = end; self.intensity = intensity
    }}
    private enum CodingKeys: String, CodingKey {{ case id, start, end, intensity }}
    public init(from decoder: Decoder) throws {{
        try rejectUnknownAssetFields(decoder, allowed: ["id", "start", "end", "intensity"])
        let c = try decoder.container(keyedBy: CodingKeys.self)
        id = try c.decode(String.self, forKey: .id)
        start = try c.decode(Double.self, forKey: .start)
        end = try c.decode(Double.self, forKey: .end)
        intensity = try c.decode(Double.self, forKey: .intensity)
        try validate()
    }}
    public func validate() throws {{
        guard !id.isEmpty, id.count <= {id_limit}, [start, end, intensity].allSatisfy(\.isFinite),
              start >= 0, end > start, end <= {time_limit},
              ({intensity_min}...{intensity_max}).contains(intensity) else {{
            throw RecipeError.invalidTimeline
        }}
    }}
}}
"""


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for output, result in [
        (OUTPUT, generate()),
        (OUTPUT.with_name("CameraPulse.generated.swift"), generate_camera()),
    ]:
        if args.check:
            if not output.exists() or output.read_text() != result:
                raise SystemExit(
                    "Native contract drift: run scripts/generate_native_text_contract.py"
                )
        else:
            output.write_text(result)
