import Foundation

// Generated by src/apps/api/scripts/generate_native_text_contract.py. Do not edit.
public struct CameraPulse: Codable, Equatable, Sendable {
    public let id: String
    public let start: Double
    public let end: Double
    public let intensity: Double
    public init(id: String, start: Double, end: Double, intensity: Double = 0.04) {
        self.id = id; self.start = start; self.end = end; self.intensity = intensity
    }
    private enum CodingKeys: String, CodingKey { case id, start, end, intensity }
    public init(from decoder: Decoder) throws {
        try rejectUnknownAssetFields(decoder, allowed: ["id", "start", "end", "intensity"])
        let c = try decoder.container(keyedBy: CodingKeys.self)
        id = try c.decode(String.self, forKey: .id)
        start = try c.decode(Double.self, forKey: .start)
        end = try c.decode(Double.self, forKey: .end)
        intensity = try c.decode(Double.self, forKey: .intensity)
        try validate()
    }
    public func validate() throws {
        guard !id.isEmpty, id.count <= 160, [start, end, intensity].allSatisfy(\.isFinite),
              start >= 0, end > start, end <= 1800,
              (0...0.08).contains(intensity) else {
            throw RecipeError.invalidTimeline
        }
    }
}
