// Generated by src/apps/api/scripts/generate_native_text_contract.py. Do not edit.
import Foundation

public struct TextAnimationPhases: Codable, Equatable, Sendable {
    public enum Edge: String, Codable, Sendable { case none, fade, pop, slide, typewriter }
    public enum Loop: String, Codable, Sendable { case none, pulse, bounce, float }
    public var entrance: Edge
    public var exit: Edge
    public var loop: Loop
    public var speed: Double
    public init(entrance: Edge = .none, exit: Edge = .none,
                loop: Loop = .none, speed: Double = 1) {
        self.entrance = entrance; self.exit = exit; self.loop = loop; self.speed = speed
    }
    private enum CodingKeys: String, CodingKey { case entrance, exit, loop, speed }
    public init(from decoder: Decoder) throws {
        try rejectUnknownAssetFields(decoder, allowed: ["entrance", "exit", "loop", "speed"])
        let c = try decoder.container(keyedBy: CodingKeys.self)
        entrance = c.contains(.entrance)
            ? try c.decode(Edge.self, forKey: .entrance) : .none
        exit = c.contains(.exit) ? try c.decode(Edge.self, forKey: .exit) : .none
        loop = c.contains(.loop) ? try c.decode(Loop.self, forKey: .loop) : .none
        speed = c.contains(.speed) ? try c.decode(Double.self, forKey: .speed) : 1
        try validate()
    }
    public func validate() throws {
        guard speed.isFinite, (0.25...3).contains(speed) else {
            throw RecipeError.invalidTimeline
        }
    }
}
