"""Cross-language parity vectors for the phone's guided label ripple.

The iPhone editor retimes per-clip label bars locally (``GuidedLabelRebase.swift``)
with the same rules as the server's ``rebase_guided_text``. The shared vector file
``src/apps/ios/Tests/Fixtures/guided_label_rebase_vectors.json`` is GENERATED by running
the server function on each case; this test asserts the file still equals the server's
output, and ``GuidedLabelRebaseTests`` asserts the Swift function against the same file.

Regenerate after a deliberate server rule change::

    cd src/apps/api && .venv/bin/python -m tests.services.test_guided_label_rebase_vectors
"""

from __future__ import annotations

import copy
import json
import types
import uuid
from pathlib import Path
from typing import Any

import pytest

from app.config import settings
from app.services.kria_editor_timeline import guided_segments_for_rows, rebase_guided_text
from tests.services._guided_timeline_fixtures import guided_job, guided_revision, label_bar

VECTORS = (
    Path(__file__).resolve().parents[5]
    / "src/apps/ios/Tests/Fixtures/guided_label_rebase_vectors.json"
)
_BASE_DURATIONS = [2.0, 2.0, 2.0, 2.0, 2.0]


def _slot(
    index: int,
    duration: float,
    *,
    slot_id: str | None = None,
    parent: str | None = None,
    transition: str = "cut",
    transition_s: float | None = None,
    clip_index: int | None = None,
) -> dict[str, Any]:
    clip = index if clip_index is None else clip_index
    return {
        "slot_id": slot_id or f"s{index + 1}",
        "parent_segment_id": parent,
        "clip_index": clip,
        "media_id": f"m{clip}",
        "in_s": 0.0,
        "duration_s": duration,
        "removed": False,
        "transition_after": transition,
        "transition_duration_s": transition_s,
    }


def _base_slots(durations: list[float] | None = None) -> list[dict[str, Any]]:
    return [_slot(i, d) for i, d in enumerate(durations or _BASE_DURATIONS)]


def _windows(slots: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Old output windows of ``slots`` (server clock) -> label bars flush on each."""
    job_id = str(uuid.uuid4())
    revision = guided_revision(job_id, count=5, source_duration_s=10.0)
    rows = copy.deepcopy(slots)
    segments = guided_segments_for_rows(revision, rows)
    return [
        label_bar(
            row["media_id"],
            row["slot_id"],
            seg["output_start_s"],
            seg["output_end_s"],
            f"Label {row['media_id']}",
        )
        for row, seg in zip(rows, segments, strict=True)
    ]


def _untouched_bars() -> list[dict[str, Any]]:
    return [
        {
            "id": "caption-1",
            "text": "spoken",
            "start_s": 0.4,
            "end_s": 1.6,
            "source_params": {"source": "caption_cue"},
        },
        {
            "id": "clip-label-narr",
            "text": "narrated",
            "start_s": 2.5,
            "end_s": 3.5,
            "source_params": {"narration_label_kind": "landmark"},
        },
        {"id": "lyric_3", "text": "la la", "start_s": 4.0, "end_s": 5.0},
    ]


def _anchored_title_bars(
    *,
    opening_start: float = 0.0,
    opening_end: float = 10.0,
    closing_start: float = 7.25,
    closing_end: float = 10.0,
    opening_segment: str = "s3",
    closing_segment: str = "s2",
) -> list[dict[str, Any]]:
    return [
        # The segment_id is deliberately stale: title IDs must be recognized
        # before the clip-segment matching branch.
        {
            "id": "guided-title",
            "text": "Opening",
            "start_s": opening_start,
            "end_s": opening_end,
            "segment_id": opening_segment,
        },
        {
            "id": "guided-closing-title",
            "text": "Closing",
            "start_s": closing_start,
            "end_s": closing_end,
            "segment_id": closing_segment,
        },
    ]


def _cases() -> list[dict[str, Any]]:
    base = _base_slots()
    flush = _windows(base)
    cases: list[dict[str, Any]] = []

    def add(
        name: str,
        old: list,
        new: list,
        labels: list,
        note: str = "",
        extra: list | None = None,
    ) -> None:
        cases.append(
            {
                "name": name,
                "note": note,
                "old_slots": old,
                "new_slots": new,
                "labels_before": labels + (extra or []) + _untouched_bars(),
            }
        )

    # The prod incident: clip 1 extended by 0.533 s, every later label stayed put.
    extend = _base_slots([2.533, 2.0, 2.0, 2.0, 2.0])
    add(
        "extend_clip1_by_0_533",
        base,
        extend,
        flush,
        "prod incident: later labels must ripple",
        [_anchored_title_bars(opening_end=2.0, closing_start=1.0)[0]],
    )

    shrink = _base_slots([1.0, 2.0, 2.0, 2.0, 2.0])
    delayed = copy.deepcopy(flush)
    delayed[0]["start_s"], delayed[0]["end_s"] = 0.6, 1.8
    add(
        "shrink_with_hand_delayed_first_label",
        base,
        shrink,
        delayed,
        "inset 0.6 / gap 0.2 scale by new_len/old_len = 0.5",
        _anchored_title_bars(opening_end=3.0, closing_start=8.0),
    )

    reorder = [base[0], base[2], base[1], base[3], base[4]]
    add(
        "reorder_clips_2_and_3",
        base,
        reorder,
        flush,
        extra=_anchored_title_bars(opening_end=3.0, closing_start=6.0),
    )

    delete = [base[0], base[2], base[3], base[4]]
    add(
        "delete_clip_2_drops_its_label",
        base,
        delete,
        flush,
        extra=[_anchored_title_bars(closing_start=8.0)[1]],
    )

    split_old = _base_slots()
    split_new = [
        base[0],
        _slot(1, 1.0, slot_id="s2"),
        _slot(1, 1.5, slot_id="s2b", parent="s2"),
        base[2],
        base[3],
        base[4],
    ]
    add("split_clip_2_label_spans_children", split_old, split_new, flush)

    separated = [
        base[0],
        _slot(1, 1.0, slot_id="s2"),
        base[2],
        _slot(1, 1.5, slot_id="s2b", parent="s2"),
        base[3],
        base[4],
    ]
    add("split_children_not_adjacent_follow_first_only", split_old, separated, flush)

    near = copy.deepcopy(flush)
    near[1]["start_s"] += 0.02
    near[1]["end_s"] -= 0.02
    add("near_flush_within_tolerance_snaps_to_window", base, extend, near)

    tiny = _base_slots([0.167, 2.0, 2.0, 2.0, 2.0])
    delayed_tiny = copy.deepcopy(flush)
    delayed_tiny[0]["start_s"], delayed_tiny[0]["end_s"] = 0.5, 1.5
    add("tiny_window_takes_whole_window", base, tiny, delayed_tiny)

    clamp = _base_slots([0.3, 2.0, 2.0, 2.0, 2.0])
    delayed_clamp = copy.deepcopy(flush)
    delayed_clamp[0]["start_s"], delayed_clamp[0]["end_s"] = 1.2, 1.9
    add("hand_delayed_label_clamped_inside_short_window", base, clamp, delayed_clamp)

    dissolve_new = _base_slots()
    dissolve_new[0] = _slot(0, 2.0, transition="crossfade", transition_s=0.3)
    add("transition_overlap_shifts_later_windows", base, dissolve_new, flush)

    media_only = copy.deepcopy(flush)
    for bar in media_only:
        bar.pop("segment_id")
    add("media_link_without_segment_id_follows_by_overlap", base, extend, media_only)

    add(
        "tiny_total_title_min_duration",
        _base_slots([0.1, 0.1, 0.1, 0.1, 0.1]),
        _base_slots([0.1, 0.1, 0.1, 0.1, 0.1]),
        _windows(_base_slots([0.1, 0.1, 0.1, 0.1, 0.1])),
        "anchored titles keep the server minimum bar duration in a tiny timeline",
        _anchored_title_bars(opening_end=0.05, closing_start=0.45, closing_end=0.5),
    )

    add("full_duration_and_closing_titles_extend", base, extend, _anchored_title_bars())
    inset_titles = _anchored_title_bars(
        opening_start=2.5,
        opening_end=3.5,
        closing_start=6.5,
        closing_end=7.5,
    )
    for name, slots in [
        ("extend", extend),
        ("shrink", shrink),
        ("reorder", reorder),
        ("delete_anchor", delete),
        ("split", split_new),
        ("crossfade", dissolve_new),
    ]:
        add(f"inset_titles_project_{name}", base, slots, inset_titles)
    trimmed_source = copy.deepcopy(base)
    trimmed_source[1]["in_s"] = 1.0
    trimmed_source[1]["duration_s"] = 1.0
    add("inset_title_source_trim_clamps", base, trimmed_source, inset_titles)
    add(
        "title_ids_use_actual_edges",
        base,
        extend,
        _anchored_title_bars(
            opening_start=8.0, opening_end=10.0, closing_start=0.0, closing_end=2.0
        ),
    )

    return cases


def compute(case: dict[str, Any]) -> list[dict[str, Any]]:
    """Run the SERVER's rebase on ``case`` and project to the compared fields."""
    job_id = str(uuid.uuid4())
    revision = guided_revision(job_id, count=5, source_duration_s=10.0)
    bars = copy.deepcopy(case["labels_before"])
    job, variant = guided_job(revision, copy.deepcopy(bars), job_id)
    old_rows = copy.deepcopy(case["old_slots"])
    old_segments = guided_segments_for_rows(revision, old_rows)
    for row, seg in zip(old_rows, old_segments, strict=True):
        row["output_start_s"], row["output_end_s"] = seg["output_start_s"], seg["output_end_s"]
    state = types.SimpleNamespace(
        slots=copy.deepcopy(case["new_slots"]),
        initial_slots=old_rows,
        text=bars,
        job=job,
        variant=variant,
        changed=set(),
        changes=[],
        sound_effects=[],
        visual_blocks=None,
    )
    rebase_guided_text(state, revision)
    out = []
    for bar in state.text:
        row = {
            "id": bar["id"],
            "start_s": round(bar["start_s"], 3),
            "end_s": round(bar["end_s"], 3),
        }
        if bar.get("segment_id"):
            row["segment_id"] = bar["segment_id"]
        out.append(row)
    return out


def build_vectors() -> dict[str, Any]:
    cases = _cases()
    for case in cases:
        case["labels_after"] = compute(case)
    return {"tolerance_s": 0.002, "cases": cases}


@pytest.fixture(autouse=True)
def _transitions(monkeypatch):
    monkeypatch.setattr(settings, "edit_transitions_enabled", True, raising=False)


def test_vectors_match_server_rebase() -> None:
    assert VECTORS.exists(), "run this module as a script to generate the vector file"
    shared = json.loads(VECTORS.read_text())
    assert shared == json.loads(json.dumps(build_vectors())), (
        "shared vectors drifted from rebase_guided_text; regenerate deliberately"
    )


def test_incident_vector_shifts_every_later_label() -> None:
    case = next(c for c in _cases() if c["name"] == "extend_clip1_by_0_533")
    after = {row["id"]: row for row in compute(case)}
    assert after["clip-label-media-m0"]["end_s"] == pytest.approx(2.533, abs=1e-3)
    for index in range(1, 5):
        row = after[f"clip-label-media-m{index}"]
        assert row["start_s"] == pytest.approx(2.533 + 2.0 * (index - 1), abs=1e-3)


if __name__ == "__main__":  # pragma: no cover - regeneration entry point
    settings.edit_transitions_enabled = True
    VECTORS.write_text(json.dumps(build_vectors(), indent=2) + "\n")
    print(f"wrote {VECTORS}")
