"""No-stacked-text invariant tests for the dynamic crossfade scheduler.

Two product invariants are enforced (see plan §5):

  Level 1 — no double-bright overlap (α > 0.85 on two overlays simultaneously)
  Level 2 — no stacked READABLE same-slot text (α > 0.65 on two overlays in
            the same visual slot simultaneously)

A fix that solves Level 2 solves Level 1 for free; the reverse is not true.

These tests replay the actual Skia alpha curves (`_lyric_line_alpha`) over
fixtures generated by `inject_lyric_overlays`. They were authored to FAIL on
pre-fix `main` (the Mirea bug). On the patched scheduler + renderer pair,
all of them must pass.

The unit-partition test scopes tightly — applies ONLY to pairs whose final
§1d decision is "crossfade" (sqrt curve + matched durations + actual
emitted overlap equals the matched duration). Sparse pairs, hard-cut
fallbacks, solo-demoted reconciliation results, and override-skipped
pairs are out of scope; Level 1/Level 2 cover those instead.
"""

from __future__ import annotations

import json
from itertools import combinations
from pathlib import Path

import pytest

from app.config import settings
from app.pipeline.lyric_injector import apply_lyric_line_overrides, inject_lyric_overlays
from app.pipeline.text_overlay_skia import _lyric_line_alpha

DOUBLE_BRIGHT_ALPHA = 0.85  # Level 1
READABLE_ALPHA = 0.65  # Level 2
MIN_MIDDLE_PEAK_HOLD_MS = 80

_FRAME_S = 1.0 / 30.0
_FIXTURE_DIR = Path(__file__).resolve().parents[1] / "fixtures" / "lyric_no_stacking"


# ──────────────────────────────────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────────────────────────────────


def _cache(lines: list[tuple[str, float, float]]) -> dict:
    return {
        # Injector requires a publishable source after 2026-05-27 — see
        # `_INJECTOR_ALLOWED_SOURCES` in app/pipeline/lyric_injector.py.
        "source": "lrclib_synced+whisper",
        "lines": [
            {
                "text": text,
                "start_s": start,
                "end_s": end,
                "words": [{"text": text, "start_s": start, "end_s": end}],
            }
            for text, start, end in lines
        ],
    }


def _recipe(slot_durations_s: tuple[float, ...] = (20.0,)) -> dict:
    return {
        "slots": [
            {"position": i + 1, "target_duration_s": d, "text_overlays": []}
            for i, d in enumerate(slot_durations_s)
        ]
    }


def _inject(
    lines: list[tuple[str, float, float]],
    cfg_extra: dict | None = None,
    slot_durations_s: tuple[float, ...] = (20.0,),
) -> list[dict]:
    cfg = {"enabled": True, "style": "line"}
    if cfg_extra:
        cfg.update(cfg_extra)
    span_start = min(s for _, s, _ in lines) - 1.0 if lines else 0.0
    span_end = max(e for _, _, e in lines) + 1.0 if lines else sum(slot_durations_s)
    out = inject_lyric_overlays(_recipe(slot_durations_s), _cache(lines), span_start, span_end, cfg)
    return [
        o
        for slot in out["slots"]
        for o in slot.get("text_overlays", [])
        if o.get("effect") == "lyric-line"
    ]


def _alpha_at(overlay: dict, t: float) -> float:
    """Replay the actual Skia alpha curve for one overlay at absolute time t.

    `t` is in the same coordinate space as overlay["start_s"]/"end_s"
    (slot-relative seconds — the scheduler emits these).
    """
    s, e = overlay["start_s"], overlay["end_s"]
    if t < s or t > e:
        return 0.0
    return _lyric_line_alpha(overlay, t - s, e - s)


def _same_visual_slot(o1: dict, o2: dict) -> bool:
    """Two overlays share a visual slot iff they would render in the same
    on-screen position (same y_frac, same text_anchor). lyric-line overlays
    all share the same default slot by design; the helper handles the
    general case so a future overlay-style change can't silently bypass."""
    return o1.get("position_y_frac") == o2.get("position_y_frac") and o1.get(
        "text_anchor", "center"
    ) == o2.get("text_anchor", "center")


def _event_boundary_times(overlays: list[dict]) -> list[float]:
    """Yield every event boundary (start, fade-in end, fade-out start, end,
    midpoint) plus ±one frame around each, plus a coarse 5 ms fill grid."""
    seen: set[float] = set()
    if not overlays:
        return []
    for o in overlays:
        s, e = o["start_s"], o["end_s"]
        fade_in_end = s + (o.get("fade_in_ms", 0) / 1000.0)
        fade_out_start = e - (o.get("fade_out_ms", 0) / 1000.0)
        for t in (s, fade_in_end, (s + e) / 2.0, fade_out_start, e):
            for delta in (-_FRAME_S, 0.0, _FRAME_S):
                seen.add(round(t + delta, 6))
    lo = min(o["start_s"] for o in overlays) - 0.05
    hi = max(o["end_s"] for o in overlays) + 0.05
    t = lo
    while t < hi:
        seen.add(round(t, 6))
        t += 0.005
    return sorted(seen)


def _active_alphas(overlays: list[dict], t: float) -> list[tuple[dict, float]]:
    return [(o, _alpha_at(o, t)) for o in overlays if _alpha_at(o, t) > 0]


# ──────────────────────────────────────────────────────────────────────────
# Level 1 / Level 2 — the user-visible invariants
# ──────────────────────────────────────────────────────────────────────────


def test_level1_no_double_bright_pair_anywhere() -> None:
    """No t may have any pair of active lyric overlays both at α > 0.85.
    Pre-fix Mirea fails this around 12.75–12.85 s (slot-relative ~1.25–1.35)."""
    overlays = _inject(
        [
            ("this year we've had to lose", 12.4, 13.0),
            ("our space we've lost", 13.1, 14.3),
        ]
    )
    for t in _event_boundary_times(overlays):
        active = _active_alphas(overlays, t)
        for (_o1, a1), (_o2, a2) in combinations(active, 2):
            assert not (a1 > DOUBLE_BRIGHT_ALPHA and a2 > DOUBLE_BRIGHT_ALPHA), (
                f"L1 double-bright at t={t:.3f}s: A={a1:.2f}, B={a2:.2f}"
            )


def test_level2_no_stacked_readable_same_slot_anywhere() -> None:
    """No t may have any same-slot pair of active overlays both at α > 0.65.
    Pre-fix Mirea fails this for ~177 ms; duration-matching-only fix still
    fails for ~137 ms; the curve-switch fix passes."""
    overlays = _inject(
        [
            ("this year we've had to lose", 12.4, 13.0),
            ("our space we've lost", 13.1, 14.3),
        ]
    )
    for t in _event_boundary_times(overlays):
        active = _active_alphas(overlays, t)
        for (o1, a1), (o2, a2) in combinations(active, 2):
            if _same_visual_slot(o1, o2):
                assert not (a1 > READABLE_ALPHA and a2 > READABLE_ALPHA), (
                    f"L2 same-slot readable stacking at t={t:.3f}s: {a1:.2f}, {a2:.2f}"
                )


# ──────────────────────────────────────────────────────────────────────────
# Unit-partition — the mathematical guard against future drift
# ──────────────────────────────────────────────────────────────────────────


def _is_pure_crossfade_pair(a: dict, b: dict) -> bool:
    """A pair is in scope for unit-partition iff all of:
    - a.fade_out_curve == "sqrt"
    - a.fade_out_ms == b.fade_in_ms
    - actual overlap (b.start_s..a.end_s) equals a.fade_out_ms / 1000
    """
    if a.get("fade_out_curve") != "sqrt":
        return False
    if a.get("fade_out_ms") != b.get("fade_in_ms"):
        return False
    overlap_ms = (a["end_s"] - b["start_s"]) * 1000.0
    return abs(overlap_ms - float(a["fade_out_ms"])) < 5.0


def test_crossfade_alpha_sum_is_unit_partition_pure_pairs_only() -> None:
    """For every pure-crossfade pair, α_a(t) + α_b(t) ≈ 1 across the overlap
    window. Mirror-symmetric curves + matched durations + matched window
    make this an algebraic identity, not an empirical observation."""
    overlays = _inject(
        [
            ("this year we've had to lose", 12.4, 13.0),
            ("our space we've lost", 13.1, 14.3),
        ]
    )
    pure_pairs = [(a, b) for a, b in zip(overlays, overlays[1:]) if _is_pure_crossfade_pair(a, b)]
    if not pure_pairs:
        pytest.skip("no pure crossfade pairs in this fixture")
    for a, b in pure_pairs:
        for t in _event_boundary_times([a, b]):
            if a["start_s"] <= t <= a["end_s"] and b["start_s"] <= t <= b["end_s"]:
                a_alpha = _alpha_at(a, t)
                b_alpha = _alpha_at(b, t)
                assert abs((a_alpha + b_alpha) - 1.0) < 0.05, (
                    f"unit-partition violated at t={t:.3f}s: "
                    f"A+B={a_alpha + b_alpha:.3f} (A={a_alpha:.2f}, B={b_alpha:.2f})"
                )


# ──────────────────────────────────────────────────────────────────────────
# Kill-switch ON ⇒ dynamic post-pass ALWAYS fires (plan §F)
#
# Pre-§F policy: cfg containing fade_in_ms or fade_out_ms was treated as
# operator intent and disabled the post-pass. Empirically the "operator
# intent" signal does not exist in production — the admin Test tab UI
# submits every form field with default values on every render, and
# effective_lyrics_config() merges them into the Job row's
# lyrics_config_effective before inject_lyric_overlays sees it. The
# override gate then silently disabled the dynamic post-pass for every
# preview job in the wild — restoring the exact stacking PR #343 was
# supposed to fix.
#
# New contract: while LYRIC_DYNAMIC_CROSSFADE_ENABLED is True, the
# dynamic post-pass fires for every consecutive pair, regardless of what
# cfg contains. The operator's only rollback is the kill switch
# (process-wide flag flip), which IS still byte-identical to pre-fix
# `main` — pinned by test_kill_switch_disabled_reproduces_pre_fix_output.
# ──────────────────────────────────────────────────────────────────────────


@pytest.mark.parametrize(
    "cfg_extra, name",
    [
        ({"fade_in_ms": 175, "fade_out_ms": 175}, "both_ms"),
        ({"fade_in_ms": 175}, "only_in_ms"),
        ({"fade_out_ms": 175}, "only_out_ms"),
        # _s aliases — the legacy form of the same fields, accepted by
        # `_resolve_fade_ms`. Must also be overridden by the post-pass.
        ({"fade_in_s": 0.175, "fade_out_s": 0.175}, "both_s"),
        ({"fade_in_s": 0.175}, "only_in_s"),
        # The 0 case — pre-fix kill-switch idiom. Under §F the post-pass
        # still fires (the kill switch is the proper rollback path), so
        # caller's 0 is overridden.
        ({"fade_in_ms": 0, "fade_out_ms": 0}, "both_zero_ms"),
        ({"fade_in_s": 0.0}, "fade_in_s_zero"),
        # Mixed _ms + _s — _s wins in _resolve_fade_ms, both should still
        # be overridden by the post-pass.
        ({"fade_in_s": 0.2, "fade_out_ms": 100}, "mixed_s_and_ms"),
    ],
)
def test_dynamic_post_pass_fires_regardless_of_explicit_fade_cfg(
    cfg_extra: dict, name: str
) -> None:
    """Caller-set fade values in cfg do NOT disable the dynamic post-pass.
    The matched-window math always wins while the kill switch is on,
    regardless of which fade-cfg permutation the caller submits:
      - fade_in_ms only / fade_out_ms only / both
      - fade_in_s / fade_out_s (legacy aliases)
      - fade_in_ms=0 / fade_out_ms=0 (legacy "kill via cfg" idiom)
      - mixed _ms + _s

    The override gate was the PR #343 regression. There is exactly one
    rollback path: settings.lyric_dynamic_crossfade_enabled = False
    (whole-system, byte-identical to pre-fix). See plan §F."""
    overlays = _inject(
        [
            ("this year we've had to lose", 12.4, 13.0),
            ("our space we've lost", 13.1, 14.3),
        ],
        cfg_extra=cfg_extra,
    )
    got_curve = overlays[0].get("fade_out_curve")
    assert got_curve == "sqrt", (
        f"{name}: post-pass should fire regardless of cfg, got curve={got_curve!r}"
    )
    assert overlays[0]["fade_out_ms"] == overlays[1]["fade_in_ms"], (
        f"{name}: matched-window math must produce equal fade durations"
    )
    # The caller's value is NOT honored when the post-pass fires — that's
    # the new contract. Verify none of the caller's specified values leaked
    # through verbatim. (175 → matched-window value ≠ 175.)
    for key, val in cfg_extra.items():
        if key == "fade_in_ms":
            assert overlays[1]["fade_in_ms"] != val or val == 0, (
                f"{name}: caller's {key}={val} was honored verbatim"
            )
        if key == "fade_out_ms":
            assert overlays[0]["fade_out_ms"] != val or val == 0, (
                f"{name}: caller's {key}={val} was honored verbatim"
            )


def test_post_pass_fires_for_admin_preview_effective_cfg() -> None:
    """REGRESSION for the PR #343 failure observed on prod job
    5a71226e-8104-404c-b8d1-b8d1f71a6414 (Mirea lyrics preview).

    The admin Test tab UI submits a LyricsConfigOverride with form-default
    fade values on every render. `create_admin_lyrics_preview` merges them
    via `effective_lyrics_config()` and saves the result to the Job row's
    `assembly_plan["lyrics_config_effective"]`. The lyrics_preview_task
    then passes that dict to `inject_lyric_overlays`. Under PR #343's
    `_caller_key_set` snapshot, the presence of `fade_in_ms` /
    `fade_out_ms` in cfg silently disabled the dynamic post-pass and
    restored legacy stacking — which the user observed at t≈16s in the
    rendered MP4 with both 'Our space, we've lost' and 'We've lost
    dancing' simultaneously readable.

    This fixture is the exact `lyrics_config_effective` shape pulled from
    the prod DB for that job. The dynamic post-pass MUST fire on it."""
    cfg = {
        "style": "line",
        "enabled": True,
        # Form-default values the admin UI sent — operator did NOT pin these
        "fade_in_ms": 150,
        "fade_out_ms": 250,
        "pre_roll_s": 0.1,
        "post_dwell_s": 1.0,
        "next_line_gap_s": 0.1,
        "hold_to_next_threshold_ms": 500,
        "position": "bottom",
        "text_size": "medium",
        "font_style": "sans",
        "outline_px": 2,
        "text_color": "#FFFFFF",
        "highlight_color": "#FFFF00",
    }
    # Use the exact temporal-overlap pair from the failing render: L2 ends
    # at 16.680 but L3 starts at 16.430 (negative audio gap of 250 ms).
    overlays = _inject(
        [
            ("Our space, we've lost", 12.540, 16.680),
            ("We've lost dancing", 16.430, 17.240),
        ],
        cfg_extra=cfg,
    )
    # The post-pass MUST have fired — this assertion is what fails on
    # PR #343 and passes after the override-gate drop.
    assert overlays[0].get("fade_out_curve") == "sqrt", (
        "Admin-preview effective_lyrics_config shape silently disabled the "
        "dynamic post-pass on PR #343 — the empirical bug that re-shipped."
    )
    assert overlays[0]["fade_out_ms"] == overlays[1]["fade_in_ms"]
    # Level 2 (no readable stacked text) must hold across the boundary.
    for t in _event_boundary_times(overlays):
        active = _active_alphas(overlays, t)
        for (o1, a1), (o2, a2) in combinations(active, 2):
            if _same_visual_slot(o1, o2):
                assert not (a1 > READABLE_ALPHA and a2 > READABLE_ALPHA), (
                    f"L2 violated at t={t:.3f}s — the regression from PR #343 "
                    f"is back: A={a1:.2f}, B={a2:.2f}"
                )


# ──────────────────────────────────────────────────────────────────────────
# Short-line hard-cut fallback (plan §1g)
# ──────────────────────────────────────────────────────────────────────────


def test_short_line_takes_hard_cut_fallback() -> None:
    """A 0.08 s vocal hit cannot crossfade safely. Hard cut — no curve tag,
    nxt.section_start re-anchored so the two overlays do not visually
    overlap. Level 2 must hold geometrically, not by curve magic."""
    overlays = _inject([("oh!", 12.92, 13.00), ("nah!", 13.05, 13.25)])
    # Outgoing line must NOT carry the curve tag (key absent).
    assert "fade_out_curve" not in overlays[0]
    # Level 2 still holds across the timeline.
    for t in _event_boundary_times(overlays):
        active = _active_alphas(overlays, t)
        for (o1, a1), (o2, a2) in combinations(active, 2):
            if _same_visual_slot(o1, o2):
                assert not (a1 > READABLE_ALPHA and a2 > READABLE_ALPHA), (
                    f"L2 violated in hard-cut fallback at t={t:.3f}s"
                )


# ──────────────────────────────────────────────────────────────────────────
# Dense three-line — middle line readability + no triple stack
# ──────────────────────────────────────────────────────────────────────────


@pytest.mark.parametrize(
    "lines",
    [
        [("A", 10.00, 10.40), ("B", 10.50, 10.80), ("C", 10.90, 11.30)],
        [("A", 10.00, 10.30), ("B", 10.35, 10.55), ("C", 10.60, 10.90)],
    ],
)
def test_three_line_middle_remains_readable(lines: list[tuple[str, float, float]]) -> None:
    """In dense A → B → C, B has both fade-in (A→B) and fade-out (B→C). Their
    sum must fit B's visible duration with room for a real peak hold. Either
    the short-line outgoing clamp (§1b) or the §1c reconciliation pass
    guarantees this; this test pins it."""
    overlays = _inject(lines)
    assert len(overlays) == 3
    B = overlays[1]
    B_visible_ms = (B["end_s"] - B["start_s"]) * 1000
    fi = int(B.get("fade_in_ms", 0))
    fo = int(B.get("fade_out_ms", 0))
    assert fi + fo <= B_visible_ms - MIN_MIDDLE_PEAK_HOLD_MS + 5, (
        f"middle B fade sum {fi}+{fo}={fi + fo} ms exceeds budget "
        f"{B_visible_ms - MIN_MIDDLE_PEAK_HOLD_MS} ms (visible {B_visible_ms} ms)"
    )
    # B must reach near-peak alpha somewhere in its window.
    B_peak = max(
        (_alpha_at(B, t) for t in _event_boundary_times([B]) if B["start_s"] <= t <= B["end_s"]),
        default=0.0,
    )
    assert B_peak >= 0.95, f"middle B never reaches peak alpha (max {B_peak:.2f})"
    # No three overlays simultaneously readable.
    for t in _event_boundary_times(overlays):
        readable = [o for o, a in _active_alphas(overlays, t) if a > READABLE_ALPHA]
        assert len(readable) <= 1, (
            f"{len(readable)} lyric overlays readable simultaneously at t={t:.3f}s"
        )
    # No same-slot pair simultaneously readable.
    for t in _event_boundary_times(overlays):
        active = _active_alphas(overlays, t)
        for (o1, a1), (o2, a2) in combinations(active, 2):
            if _same_visual_slot(o1, o2):
                assert not (a1 > READABLE_ALPHA and a2 > READABLE_ALPHA), (
                    f"same-slot readable stacking at t={t:.3f}s"
                )


# ──────────────────────────────────────────────────────────────────────────
# Hard-cut re-anchoring must not stale a later pair candidate
# ──────────────────────────────────────────────────────────────────────────


def test_hard_cut_followed_by_pair_does_not_stale_later_candidate() -> None:
    """When A→B is hard_cut or solo_demoted, B.section_start_s is re-anchored
    AFTER pair candidates were computed. The B→C candidate must still
    produce a valid geometry — no readable stacking, B reaches peak alpha,
    B fade sum fits inside B's possibly-newly-shrunk visible window."""
    overlays = _inject(
        [
            ("a!", 12.92, 13.00),  # too short → triggers hard_cut for A→B
            ("bee", 13.05, 13.65),
            ("see", 13.75, 14.30),
        ]
    )
    assert len(overlays) == 3
    B = overlays[1]
    B_visible_ms = (B["end_s"] - B["start_s"]) * 1000
    fi = int(B.get("fade_in_ms", 0))
    fo = int(B.get("fade_out_ms", 0))
    assert fi + fo <= B_visible_ms - MIN_MIDDLE_PEAK_HOLD_MS + 5, (
        f"B fade sum {fi}+{fo} exceeds budget after hard-cut re-anchor"
    )
    B_peak = max(
        (_alpha_at(B, t) for t in _event_boundary_times([B]) if B["start_s"] <= t <= B["end_s"]),
        default=0.0,
    )
    assert B_peak >= 0.95, f"B never reaches peak after re-anchor (max {B_peak:.2f})"
    for t in _event_boundary_times(overlays):
        active = _active_alphas(overlays, t)
        for (o1, a1), (o2, a2) in combinations(active, 2):
            if _same_visual_slot(o1, o2):
                assert not (a1 > READABLE_ALPHA and a2 > READABLE_ALPHA), (
                    f"L2 violated after hard-cut re-anchor at t={t:.3f}s"
                )


# ──────────────────────────────────────────────────────────────────────────
# Kill switch — true legacy rollback (byte-identical to pre-fix snapshot)
# ──────────────────────────────────────────────────────────────────────────


_KILL_SWITCH_SNAPSHOTS = [
    (
        "two_line_default_gap_pre_fix.json",
        [("First", 1.0, 2.0), ("Second", 2.3, 3.0)],
        (10.0,),
    ),
    (
        "three_line_dense_pre_fix.json",
        [("A", 10.0, 10.4), ("B", 10.5, 10.8), ("C", 10.9, 11.3)],
        (15.0,),
    ),
    (
        "short_line_hit_pre_fix.json",
        [("oh!", 12.92, 13.00), ("nah!", 13.05, 13.25)],
        (15.0,),
    ),
]


@pytest.mark.parametrize("snapshot_name, lines, slot_durations_s", _KILL_SWITCH_SNAPSHOTS)
def test_kill_switch_disabled_reproduces_pre_fix_output(
    snapshot_name: str,
    lines: list[tuple[str, float, float]],
    slot_durations_s: tuple[float, ...],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """settings.lyric_dynamic_crossfade_enabled = False must reproduce
    pre-fix scheduler output byte-identically — no `fade_out_curve` key,
    same fade durations, same section starts/ends, same set of keys on
    every overlay. Snapshots committed under
    tests/fixtures/lyric_no_stacking/*_pre_fix.json."""
    monkeypatch.setattr(settings, "lyric_dynamic_crossfade_enabled", False)
    got = _inject(lines, slot_durations_s=slot_durations_s)
    snapshot = json.loads((_FIXTURE_DIR / snapshot_name).read_text())
    expected = snapshot["overlays"]
    assert len(got) == len(expected), (
        f"overlay count drift: got {len(got)} expected {len(expected)}"
    )
    for i, (got_o, want_o) in enumerate(zip(got, expected)):
        assert "fade_out_curve" not in got_o, (
            f"kill-switch leaked fade_out_curve into overlay [{i}]: {got_o.get('fade_out_curve')!r}"
        )
        assert set(got_o.keys()) - {"lyric_line_key"} == set(want_o.keys()), (
            f"kill-switch added/removed keys on overlay [{i}]: "
            f"{set(got_o.keys()) ^ set(want_o.keys())}"
        )
        assert got_o.get("lyric_line_key") == f"L{i}"
        for field in (
            "start_s",
            "end_s",
            "fade_in_ms",
            "fade_out_ms",
            "lyric_line_id",
            "lyric_segment_index",
            "lyric_segment_count",
        ):
            assert got_o.get(field) == want_o.get(field), (
                f"kill-switch drift on overlay [{i}].{field}: "
                f"got {got_o.get(field)!r} want {want_o.get(field)!r}"
            )


@pytest.mark.parametrize("enabled", [True, False])
def test_text_override_does_not_change_line_schedule_geometry(
    enabled: bool,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setattr(settings, "lyric_dynamic_crossfade_enabled", enabled)
    lines = [
        ("this year we've had to lose", 12.4, 13.0),
        ("our space we've lost", 13.1, 14.3),
        ("but we still move", 14.5, 15.2),
    ]
    cfg = {"enabled": True, "style": "line"}
    span_start = min(s for _, s, _ in lines) - 1.0
    span_end = max(e for _, _, e in lines) + 1.0
    baseline = inject_lyric_overlays(_recipe(), _cache(lines), span_start, span_end, cfg)
    overridden_cache = apply_lyric_line_overrides(
        _cache(lines),
        {
            "L0": {
                "text": "that year they had to choose",
                "orig_text": "this year we've had to lose",
                "orig_start_s": 12.4,
            }
        },
    )
    edited = inject_lyric_overlays(_recipe(), overridden_cache, span_start, span_end, cfg)

    baseline_geometry = [
        {
            key: overlay.get(key)
            for key in (
                "start_s",
                "end_s",
                "fade_in_ms",
                "fade_out_ms",
                "fade_out_curve",
                "lyric_line_id",
                "lyric_line_key",
                "lyric_segment_index",
                "lyric_segment_count",
            )
        }
        for slot in baseline["slots"]
        for overlay in slot.get("text_overlays", [])
    ]
    edited_geometry = [
        {
            key: overlay.get(key)
            for key in (
                "start_s",
                "end_s",
                "fade_in_ms",
                "fade_out_ms",
                "fade_out_curve",
                "lyric_line_id",
                "lyric_line_key",
                "lyric_segment_index",
                "lyric_segment_count",
            )
        }
        for slot in edited["slots"]
        for overlay in slot.get("text_overlays", [])
    ]
    assert edited_geometry == baseline_geometry


# ──────────────────────────────────────────────────────────────────────────
# Parametrized grid — Level 1 / Level 2 across realistic gaps × durations
# ──────────────────────────────────────────────────────────────────────────


# ──────────────────────────────────────────────────────────────────────────
# Style-set defaults must NOT spoof user override — the regression class that
# would silently kill the fix for nearly every production track.
# ──────────────────────────────────────────────────────────────────────────


@pytest.mark.parametrize(
    "style_set_id",
    [
        "lyric_line_calm",
        "travel_editorial",
        "lifestyle_clean",
        "high_fashion",
        "bold_statement",
        "film_mono",
    ],
)
def test_style_set_defaults_do_not_spoof_user_override(style_set_id: str) -> None:
    """Every shipped `lyric_line` style set defines fade_in_ms + fade_out_ms in
    its `timing` block. `_apply_style_set_defaults` writes those into cfg.
    The dynamic-crossfade post-pass MUST treat those as defaults (not user
    overrides) and still fire — otherwise the fix is dead code for nearly
    every production track. This is the bug the adversarial review caught."""
    overlays = _inject(
        [
            ("this year we've had to lose", 12.4, 13.0),
            ("our space we've lost", 13.1, 14.3),
        ],
        cfg_extra={"style_set_id": style_set_id},
    )
    # First overlay must be tagged for sqrt crossfade. If the style-set's
    # fade_in_ms/fade_out_ms defaults spoofed user override, the post-pass
    # would have skipped this pair and no curve tag would be emitted.
    assert overlays[0].get("fade_out_curve") == "sqrt", (
        f"style_set={style_set_id}: dynamic post-pass did NOT fire — style-set "
        f"defaults were treated as user override"
    )
    # Matched durations confirm the §1d apply step ran.
    assert overlays[0]["fade_out_ms"] == overlays[1]["fade_in_ms"]
    # Level 2 must hold for the rendered timeline.
    for t in _event_boundary_times(overlays):
        active = _active_alphas(overlays, t)
        for (o1, a1), (o2, a2) in combinations(active, 2):
            if _same_visual_slot(o1, o2):
                assert not (a1 > READABLE_ALPHA and a2 > READABLE_ALPHA), (
                    f"L2 violated at t={t:.3f}s with style_set={style_set_id}"
                )


def test_explicit_cfg_fade_with_style_set_still_fires_post_pass() -> None:
    """The §F override-gate drop applies regardless of style_set_id. Even
    when a caller explicitly pins fade_in_ms in cfg AND specifies a style
    set, the dynamic post-pass still runs and overrides both with the
    matched-window math. This was the inverse of the PR #343 contract."""
    overlays = _inject(
        [
            ("this year we've had to lose", 12.4, 13.0),
            ("our space we've lost", 13.1, 14.3),
        ],
        cfg_extra={
            "style_set_id": "lyric_line_calm",
            "fade_in_ms": 175,
        },
    )
    assert overlays[0].get("fade_out_curve") == "sqrt"
    assert overlays[0]["fade_out_ms"] == overlays[1]["fade_in_ms"]
    # Caller's 175 is overridden by the crossfade math — not honored.
    assert overlays[1]["fade_in_ms"] != 175


@pytest.mark.parametrize("gap_s", [0.0, 0.05, 0.1, 0.2, 0.4, 0.8])
@pytest.mark.parametrize("dur_s", [0.08, 0.18, 0.4, 0.8, 1.5, 3.0])
def test_level1_and_level2_hold_across_grid(gap_s: float, dur_s: float) -> None:
    """Level 1 and Level 2 must hold across the full gap × duration grid,
    INCLUDING the short-line corners (dur_s ∈ {0.08, 0.18}) that route
    through the hard-cut fallback. If any corner regresses, this fails
    before merge — no waiver."""
    a_start = 12.0
    a_end = a_start + dur_s
    b_start = a_end + gap_s
    b_end = b_start + 1.0
    overlays = _inject([("A", a_start, a_end), ("B", b_start, b_end)])
    for t in _event_boundary_times(overlays):
        active = _active_alphas(overlays, t)
        for (o1, a1), (o2, a2) in combinations(active, 2):
            assert not (a1 > DOUBLE_BRIGHT_ALPHA and a2 > DOUBLE_BRIGHT_ALPHA), (
                f"L1 fail dur={dur_s} gap={gap_s} t={t:.3f}: {a1:.2f}, {a2:.2f}"
            )
            if _same_visual_slot(o1, o2):
                assert not (a1 > READABLE_ALPHA and a2 > READABLE_ALPHA), (
                    f"L2 fail dur={dur_s} gap={gap_s} t={t:.3f}: {a1:.2f}, {a2:.2f}"
                )


# ──────────────────────────────────────────────────────────────────────────
# Consolidation-path coverage — the layer the unit tests above don't reach
# ──────────────────────────────────────────────────────────────────────────
#
# Everything above replays alpha over the RAW `inject_lyric_overlays` output.
# But generative + music jobs render the output of `_collect_absolute_overlays`,
# which runs two more transforms the scheduler tests never exercise:
#   1. `_consolidate_lyric_segments` merges a line's cross-slot segments by
#      `lyric_line_id` and must carry `fade_out_curve` from the last segment
#      onto the merged overlay (a curve drop here silently reverts to the 1−p²
#      stacking bug, invisible to the unit suite).
#   2. slot-relative → absolute-time rebasing across multiple beat-synced slots.
# These tests pin the no-stacking invariant at THAT layer, anchored to a real
# prod failure.


# The exact `lyrics_config_effective` shape prod feeds `inject_lyric_overlays`
# (admin Test tab / generative path): form-default fade_in_ms=150 + fade_out_ms=250
# that PR #343's `_caller_key_set` snapshot misread as user overrides and used to
# disable its own crossfade (the #344 regression). The bare {"enabled","style"}
# config bypasses that path entirely — #344's own commit names it as why #343's
# tests missed the bug. These consolidation + burn tests use the realistic shape
# so they guard the path that actually broke, not the happy path.
EFFECTIVE_CFG = {
    "style": "line",
    "enabled": True,
    "fade_in_ms": 150,
    "fade_out_ms": 250,
    "pre_roll_s": 0.1,
    "post_dwell_s": 1.0,
    "next_line_gap_s": 0.1,
    "hold_to_next_threshold_ms": 500,
    "position": "bottom",
    "text_size": "medium",
    "font_style": "sans",
    "outline_px": 2,
    "text_color": "#FFFFFF",
    "highlight_color": "#FFFF00",
}


def _inject_and_consolidate(
    lines: list[tuple[str, float, float]],
    best_start_s: float,
    best_end_s: float,
    slot_durations_s: tuple[float, ...],
    cfg: dict | None = None,
) -> list[dict]:
    """Inject, then run the real `_collect_absolute_overlays` consolidation the
    generative + music render paths use. Returns absolute-time lyric overlays.

    Defaults to the realistic `effective_lyrics_config` shape (EFFECTIVE_CFG) —
    the one that tripped PR #343's user-override gate — NOT the bare config that
    silently bypasses the dynamic post-pass."""
    from app.tasks.template_orchestrate import _collect_absolute_overlays

    out = inject_lyric_overlays(
        _recipe(slot_durations_s),
        _cache(lines),
        best_start_s,
        best_end_s,
        dict(cfg or EFFECTIVE_CFG),
    )
    steps = [{"clip_id": f"c{i}", "slot": slot} for i, slot in enumerate(out["slots"])]
    abs_overlays = _collect_absolute_overlays(
        steps, list(slot_durations_s), None, "", is_agentic=True
    )
    return [o for o in abs_overlays if o.get("effect") == "lyric-line"]


# Real synced lyrics from prod track 29da2cbf ("Milky – Just The Way You Are"),
# best section 60-75s (absolute song time). Consecutive sustained "Do do" lines
# OVERLAP each other (62.92 < 63.19), and a generative job (901fe271) rendered
# them as four overlays stacked at bottom/0.80 — the reported clash. Captured
# before #343's dynamic-crossfade scheduler landed; pinned here so the
# consolidation path can never regress back to that frame.
_MILKY_PROD_LINES = [
    ("Just the way you are", 58.22, 60.12),
    ("Do do do do do do do do", 60.12, 63.19),
    ("Do do do do do do do do", 62.92, 66.54),
    ("And it goes", 66.74, 67.15),
    ("Do do do do do do do do", 67.32, 70.24),
    ("Do do do do do do do do", 70.42, 73.83),
    ("And it goes", 74.1, 74.72),
]


def _assert_no_stacking_through_consolidation(overlays: list[dict], label: str) -> None:
    assert overlays, f"{label}: expected consolidated lyric overlays"
    for t in _event_boundary_times(overlays):
        active = _active_alphas(overlays, t)
        for (o1, a1), (o2, a2) in combinations(active, 2):
            assert not (a1 > DOUBLE_BRIGHT_ALPHA and a2 > DOUBLE_BRIGHT_ALPHA), (
                f"{label}: L1 double-bright at t={t:.3f}s — {a1:.2f}, {a2:.2f} "
                f"({o1['text'][:16]!r} / {o2['text'][:16]!r})"
            )
            if _same_visual_slot(o1, o2):
                assert not (a1 > READABLE_ALPHA and a2 > READABLE_ALPHA), (
                    f"{label}: L2 same-slot readable stacking at t={t:.3f}s — "
                    f"{a1:.2f}, {a2:.2f} ({o1['text'][:16]!r} / {o2['text'][:16]!r})"
                )


@pytest.mark.parametrize(
    "label, best_start, best_end, slot_durations",
    [
        # Footage-trimmed single clip — the exact shape of prod job 901fe271.
        ("milky footage-trimmed 7.5s", 60.0, 67.5, (7.5,)),
        # Multi-slot beat-synced cuts — cross-slot segment merge + curve carry.
        ("milky full section 2x7.5s", 60.0, 75.0, (7.5, 7.5)),
        ("milky full section 6x2.5s", 60.0, 75.0, (2.5, 2.5, 2.5, 2.5, 2.5, 2.5)),
    ],
)
def test_milky_prod_lines_no_stacking_through_consolidation(
    label: str, best_start: float, best_end: float, slot_durations: tuple[float, ...]
) -> None:
    """Overlapping synced source lines must not stack at the render layer the
    generative + music paths actually use (post-consolidation absolute time).
    Regression for prod job 901fe271; complements #343's inject-level suite."""
    overlays = _inject_and_consolidate(_MILKY_PROD_LINES, best_start, best_end, slot_durations)
    _assert_no_stacking_through_consolidation(overlays, label)


def test_consolidation_carries_fade_out_curve_onto_merged_overlay() -> None:
    """A line that (a) spans two slots AND (b) crossfades into the next line
    must keep `fade_out_curve="sqrt"` on its merged overlay. The curve lives
    on the line's LAST segment (in slot 1); `_consolidate_lyric_segments` must
    carry it onto the merged result. Dropping it on merge silently reverts to
    the 1−p² curve that caused the stacking bug — invisible to the inject-level
    suite because it never consolidates.

    (A lone line with no successor correctly has no curve — #343 emits sqrt
    only on a crossfade decision — so the spanning line needs a follower.)"""
    overlays = _inject_and_consolidate(
        [
            ("a line that spans both slots", 60.5, 63.5),  # crosses the 2.5s seam
            ("the following line here", 63.0, 64.8),  # A crossfades into this
        ],
        60.0,
        65.0,
        (2.5, 2.5),
    )
    merged = [o for o in overlays if o["text"] == "a line that spans both slots"]
    assert len(merged) == 1, "cross-slot segments should consolidate to one overlay"
    assert merged[0].get("fade_out_curve") == "sqrt", (
        "merged overlay lost fade_out_curve — would revert to the stacking curve"
    )
