"""KRI-548 device fixture: server-compiled Kadıköy captions for the iPhone watermark check.

``src/apps/ios/Tests/Fixtures/KRI548CaptionWatermark.json`` carries the caption text
layers ``compile_caption_layers`` builds for three real prod cues (the 2026-10-08
Kadıköy Talking edit) at the default look -- once as compiled today (re-broken around
the device watermark) and once with the KRI-548 pass switched off, the layout prod
shipped. ``CaptionWatermarkClearanceTests`` (KriaTests) exports both through the
phone engine with the real watermark and looks for caption ink in the mark's corner:
the re-broken set must leave it clear, the unbroken set must not (negative control).

This test regenerates the fixture from the compiler and fails when the checked-in
file no longer matches it.

Platform note. Skia measures glyphs through CoreText on macOS and FreeType on Linux,
and the advances differ slightly -- enough to move a line break (macOS "İlk durak /
Moda'da, deniz kenarında / …", Linux "İlk durak Moda'da, / deniz kenarında / …").
The fixture is generated on macOS: the KRI-559 journey job that runs this file and
the native test is a macOS runner, and the device itself shapes nothing (it draws the
fixture's glyph ids at the fixture's positions). So:

- everywhere: cues, canvas, keep-out, font manifest, timing, anchor, effect and run
  style must match exactly; every cue keeps its words in order; the fixture's own
  re-broken glyphs stay clear of the keep-out and its unbroken glyphs reach into it;
- on the generating platform (``generated_on``) additionally: the same line breaks,
  the same glyph ids, and positions within half a pixel.

Regenerate after a deliberate compiler change, on macOS::

    cd src/apps/api && .venv/bin/python -m tests.pipeline.test_phone_caption_watermark_fixture
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import Any

FIXTURE = (
    Path(__file__).resolve().parents[5] / "src/apps/ios/Tests/Fixtures/KRI548CaptionWatermark.json"
)
_CANVAS = {"width": 1080, "height": 1920}
# Three cues from the prod render whose first lines ran under the mark ("İlk
# durak..." lost the İ, "Üçüncü..." the Ü) or reach its band once re-broken.
_CUE_TEXTS = [
    "İlk durak Moda'da, deniz kenarında küçücük bir yer.",
    "Üçüncü ve en sevdiğim yer Yeldeğirmeni'nde.",
    "Bakın, ben günde 4 kahve içiyorum, o yüzden bu konuda biraz uzmanım.",
]
# One second per cue keeps the device export short; the pop-in settles in 0.25 s.
_CUE_SPACING_S = 1.0
_CUE_DURATION_S = 0.9
_POSITION_TOLERANCE_PX = 0.5
_RUN_STYLE_KEYS = (
    "font_asset_id",
    "font_size",
    "font_variations",
    "letter_spacing",
    "shaped",
    "fill",
    "stroke",
    "stroke_width",
    "blur_layers",
    "gradient",
)


def _cues() -> list[dict[str, Any]]:
    return [
        {
            "text": text,
            "start_s": index * _CUE_SPACING_S,
            "end_s": index * _CUE_SPACING_S + _CUE_DURATION_S,
        }
        for index, text in enumerate(_CUE_TEXTS)
    ]


def build_fixture() -> dict[str, Any]:
    """The fixture as the current compiler produces it on this platform."""
    from app.kria.render_assets import RenderAssetManifest
    from app.pipeline import phone_captions

    width, height = _CANVAS["width"], _CANVAS["height"]
    layers = phone_captions.compile_caption_layers(
        _cues(), canvas_width=width, canvas_height=height
    )
    # The pre-KRI-548 layout: the same compile with the make-room pass switched off,
    # exactly as test_phone_captions.py reproduces the prod bug.
    make_room = phone_captions._make_room_for_watermark
    phone_captions._make_room_for_watermark = lambda layers, *_a, **_k: layers
    try:
        unbroken = phone_captions.compile_caption_layers(
            _cues(), canvas_width=width, canvas_height=height
        )
    finally:
        phone_captions._make_room_for_watermark = make_room
    fonts = phone_captions.caption_font_assets([*layers, *unbroken])
    manifest = RenderAssetManifest(assets=tuple(fonts[key] for key in sorted(fonts)))
    return {
        "about": (
            "KRI-548: server-compiled phone caption layers for three prod Kadikoy cues at "
            "the default look. Generated by src/apps/api/tests/pipeline/"
            "test_phone_caption_watermark_fixture.py; do not edit by hand."
        ),
        "generated_on": sys.platform,
        "canvas": dict(_CANVAS),
        "watermark_gap_px": phone_captions._WATERMARK_GAP_PX,
        "watermark_keepout": list(phone_captions.watermark_keepout_rect(width, height)),
        "cues": _cues(),
        "asset_manifest": manifest.model_dump(mode="json"),
        "layers": [layer.model_dump(mode="json") for layer in layers],
        "unbroken_layers": [layer.model_dump(mode="json") for layer in unbroken],
    }


def _lines(layer: dict[str, Any]) -> list[str]:
    rows: dict[float, list[str]] = {}
    for run in layer["runs"]:
        rows.setdefault(run["baseline_y"], []).append(run["text"])
    return [" ".join(rows[baseline]) for baseline in sorted(rows)]


def _portable(layer: dict[str, Any]) -> dict[str, Any]:
    """What cannot depend on the platform's glyph metrics."""
    return {
        **{key: value for key, value in layer.items() if key != "runs"},
        "words": " ".join(_lines(layer)).split(),
        "run_styles": sorted(
            {json.dumps({key: run.get(key) for key in _RUN_STYLE_KEYS}) for run in layer["runs"]}
        ),
    }


def _assert_same_layout(shared: dict[str, Any], fresh: dict[str, Any], where: str) -> None:
    assert _lines(shared) == _lines(fresh), where
    assert len(shared["runs"]) == len(fresh["runs"]), where
    for old, new in zip(shared["runs"], fresh["runs"], strict=True):
        assert old["text"] == new["text"], where
        for key in ("x", "baseline_y"):
            assert abs(old[key] - new[key]) <= _POSITION_TOLERANCE_PX, (where, old["text"], key)
        old_glyphs, new_glyphs = old.get("glyphs") or [], new.get("glyphs") or []
        assert [g["glyph_id"] for g in old_glyphs] == [g["glyph_id"] for g in new_glyphs], where
        for a, b in zip(old_glyphs, new_glyphs, strict=True):
            assert abs(a["x"] - b["x"]) <= _POSITION_TOLERANCE_PX, (where, old["text"])
            assert abs(a["y"] - b["y"]) <= _POSITION_TOLERANCE_PX, (where, old["text"])


def _touches_keepout(layer: dict[str, Any], keepout: list[float]) -> bool:
    """Whether any run's ink (glyph outlines + outline stroke, as the device draws the
    fixture's positioned glyphs) meets the keep-out."""
    from app.kria.portable_text import PortableTextLayer
    from app.pipeline import text_overlay_skia as cloud
    from app.pipeline.phone_captions import CAPTION_FONT_FAMILY, caption_ink_box

    typeface = cloud._resolve_typeface_for_overlay({"font_family": CAPTION_FONT_FAMILY}).typeface
    left, top, right, bottom = keepout
    for run in PortableTextLayer.model_validate(layer).runs:
        ink = caption_ink_box(run, typeface)
        if (
            ink is not None
            and ink[0] < right
            and ink[2] > left
            and ink[1] < bottom
            and ink[3] > top
        ):
            return True
    return False


def test_fixture_matches_the_caption_compiler() -> None:
    assert FIXTURE.exists(), "run this module as a script to generate the fixture"
    shared = json.loads(FIXTURE.read_text())
    fresh = json.loads(json.dumps(build_fixture()))

    for key in ("canvas", "watermark_gap_px", "watermark_keepout", "cues", "asset_manifest"):
        assert shared[key] == fresh[key], f"{key} drifted; regenerate deliberately"
    for name in ("layers", "unbroken_layers"):
        assert len(shared[name]) == len(fresh[name]) == len(_CUE_TEXTS), name
        for old, new in zip(shared[name], fresh[name], strict=True):
            assert _portable(old) == _portable(new), f"{name}/{old['id']} drifted; regenerate"
    if sys.platform == shared["generated_on"]:
        for name in ("layers", "unbroken_layers"):
            for old, new in zip(shared[name], fresh[name], strict=True):
                _assert_same_layout(old, new, f"{name}/{old['id']}")


def test_fixture_rebreaks_every_cue_clear_of_the_mark_and_keeps_its_words() -> None:
    shared = json.loads(FIXTURE.read_text())
    keepout = shared["watermark_keepout"]
    for cue, layer, unbroken in zip(
        shared["cues"], shared["layers"], shared["unbroken_layers"], strict=True
    ):
        assert " ".join(_lines(layer)).split() == cue["text"].split()
        assert " ".join(_lines(unbroken)).split() == cue["text"].split()
        assert (layer["start"], layer["end"]) == (cue["start_s"], cue["end_s"])
        assert not _touches_keepout(layer, keepout), layer["id"]
    # The negative control the device test relies on: prod's layout inks the mark.
    touching = [_touches_keepout(layer, keepout) for layer in shared["unbroken_layers"]]
    assert all(touching), touching


if __name__ == "__main__":  # pragma: no cover - regeneration entry point
    for key, value in {
        "STORAGE_BUCKET": "nova-test",
        "STORAGE_PROVIDER": "gcs",
        "DATABASE_URL": "postgresql://postgres:postgres@localhost:5432/nova_test",
    }.items():
        os.environ.setdefault(key, value)
    FIXTURE.write_text(json.dumps(build_fixture(), indent=2, ensure_ascii=False) + "\n")
    print(f"wrote {FIXTURE}")
