import XCTest
@testable import Kria

/// The phone retimes per-clip label bars when clip timing changes, with the server's
/// `rebase_guided_text` rules. The vector file is generated BY the server function
/// (`tests/services/test_guided_label_rebase_vectors.py`); the same file is asserted here.
final class GuidedLabelRebaseVectorTests: XCTestCase {
    private struct Vectors: Decodable {
        struct Case: Decodable {
            let name: String
            let oldSlots: [[String: JSONValue]]
            let newSlots: [[String: JSONValue]]
            let labelsBefore: [[String: JSONValue]]
            let labelsAfter: [[String: JSONValue]]
            enum CodingKeys: String, CodingKey {
                case name; case oldSlots = "old_slots"; case newSlots = "new_slots"
                case labelsBefore = "labels_before"; case labelsAfter = "labels_after"
            }
        }
        let toleranceS: Double
        let cases: [Case]
        enum CodingKeys: String, CodingKey { case toleranceS = "tolerance_s"; case cases }
    }

    private func vectors() throws -> Vectors {
        let url = try XCTUnwrap(Bundle(for: Self.self).url(forResource: "guided_label_rebase_vectors", withExtension: "json"))
        return try JSONDecoder().decode(Vectors.self, from: Data(contentsOf: url))
    }

    static func slot(_ row: [String: JSONValue]) -> EditorTimelineSlot {
        EditorTimelineSlot(
            id: row["slot_id"]?.stringValue,
            clipIndex: Int(row["clip_index"]?.numberValue ?? 0),
            inS: row["in_s"]?.numberValue ?? 0,
            durationS: row["duration_s"]?.numberValue,
            removed: row["removed"]?.boolValue ?? false,
            parentSegmentID: row["parent_segment_id"]?.stringValue,
            transitionAfter: row["transition_after"]?.stringValue ?? "cut",
            transitionDurationS: row["transition_duration_s"]?.numberValue,
            raw: row.filter { $0.key == "media_id" }
        )
    }

    private static func element(_ row: [String: JSONValue]) -> EditorTextElement {
        EditorTextElement(
            id: row["id"]?.stringValue ?? "", text: row["text"]?.stringValue ?? "",
            startS: row["start_s"]?.numberValue ?? 0, endS: row["end_s"]?.numberValue ?? 0,
            role: row["role"]?.stringValue, raw: row
        )
    }

    func testEveryServerGeneratedVectorMatches() throws {
        let file = try vectors()
        XCTAssertGreaterThanOrEqual(file.cases.count, 10)
        for vector in file.cases {
            let before = vector.labelsBefore.map(Self.element)
            let after = GuidedLabelRebase.rebase(
                before, oldSlots: vector.oldSlots.map(Self.slot), newSlots: vector.newSlots.map(Self.slot)
            )
            XCTAssertEqual(after.map(\.id), vector.labelsAfter.compactMap { $0["id"]?.stringValue }, vector.name)
            for (actual, expected) in zip(after, vector.labelsAfter) {
                XCTAssertEqual(actual.startS, expected["start_s"]?.numberValue ?? .nan, accuracy: file.toleranceS, "\(vector.name) \(actual.id) start")
                XCTAssertEqual(actual.endS, expected["end_s"]?.numberValue ?? .nan, accuracy: file.toleranceS, "\(vector.name) \(actual.id) end")
                XCTAssertEqual(actual.raw["segment_id"]?.stringValue, expected["segment_id"]?.stringValue, "\(vector.name) \(actual.id) segment")
            }
        }
    }

    func testRebaseNeverChangesTextStyleOrPositionAndLeavesNonLabelBarsExact() throws {
        let file = try vectors()
        let vector = try XCTUnwrap(file.cases.first { $0.name == "extend_clip1_by_0_533" })
        let before = vector.labelsBefore.map(Self.element)
        let after = GuidedLabelRebase.rebase(before, oldSlots: vector.oldSlots.map(Self.slot), newSlots: vector.newSlots.map(Self.slot))
        let volatile: Set<String> = ["start_s", "end_s", "segment_id"]
        for (old, new) in zip(before, after) {
            XCTAssertEqual(old.text, new.text)
            XCTAssertEqual(old.raw.filter { !volatile.contains($0.key) }, new.raw.filter { !volatile.contains($0.key) }, old.id)
            if !GuidedLabelRebase.isClipLabel(old) { XCTAssertEqual(old, new, "\(old.id) must be untouched") }
        }
        XCTAssertEqual(after.filter(GuidedLabelRebase.isClipLabel).count, 5)
    }

    func testLabelWithNoIdentifiableSlotStaysPutOnThePhone() throws {
        let file = try vectors()
        let vector = try XCTUnwrap(file.cases.first { $0.name == "extend_clip1_by_0_533" })
        let orphan = EditorTextElement(id: "clip-label-unified-cut-9", text: "Mystery", startS: 5, endS: 6, raw: ["id": .string("clip-label-unified-cut-9")])
        let after = GuidedLabelRebase.rebase([orphan], oldSlots: vector.oldSlots.map(Self.slot), newSlots: vector.newSlots.map(Self.slot))
        XCTAssertEqual(after, [orphan])
    }

    func testEmptyNewTimelineNeverWipesTheLabels() throws {
        let vector = try XCTUnwrap(vectors().cases.first)
        let before = vector.labelsBefore.map(Self.element)
        XCTAssertEqual(GuidedLabelRebase.rebase(before, oldSlots: vector.oldSlots.map(Self.slot), newSlots: []), before)
    }
}

/// Handler-level: every clip-timing edit in the native editor carries the labels with it.
@MainActor
final class GuidedLabelRippleSessionTests: XCTestCase {
    private static let jobID = "5b1d2f0a-6c0e-4b8e-9d0a-1c2d3e4f5a6b"

    private static func slot(_ id: String, _ index: Double, transition: String = "cut") -> JSONValue {
        .object(["slot_id": .string(id), "clip_index": .number(index), "in_s": .number(0), "duration_s": .number(2),
                 "source_duration_s": .number(10), "removed": .bool(false), "transition_after": .string(transition)])
    }

    private static func label(_ n: Int, _ start: Double, _ end: Double) -> JSONValue {
        .object(["id": .string("clip-label-unified-cut-\(n)"), "text": .string("Place \(n)"), "start_s": .number(start), "end_s": .number(end),
                 "segment_id": .string("s\(n)"), "role": .string("generative_intro"), "font_family": .string("DM Sans"),
                 "size_px": .number(58), "x_frac": .number(0.5), "y_frac": .number(0.78), "color": .string("#FFF8F0")])
    }

    private static func variant() -> [String: JSONValue] {
        [
            "variant_id": .string("initial"), "render_generation_id": .string("g1"), "render_status": .string("ready"),
            "duration_s": .number(8), "output_url": .string("file:///tmp/kria-label-ripple.mp4"),
            "resolved_archetype": .string("guided_story"), "base_video_path": .string("base.mp4"),
            "editor_capabilities": .object(["timeline": .bool(true), "text_elements": .bool(true), "mix": .bool(true)]),
            "user_timeline": .object(["slots": .array((1...4).map { slot("s\($0)", Double($0 - 1)) })]),
            "text_elements": .array([
                .object(["id": .string("guided-title"), "text": .string("Weekend"), "start_s": .number(0), "end_s": .number(8), "role": .string("generative_intro")]),
                label(1, 0, 2), label(2, 2, 4), label(3, 4, 6), label(4, 6, 8),
                .object(["id": .string("caption-1"), "text": .string("spoken"), "start_s": .number(2.5), "end_s": .number(3.5),
                         "source_params": .object(["source": .string("caption_cue")])]),
            ]),
        ]
    }

    private func loaded() async -> (NativeEditorSession, EditorCommitSpy) {
        let bootstrap = DraftSnapshot(draftID: "d1", itemID: "item", variantKey: "initial", draftRevision: 1, snapshotHash: "h", etag: "e",
            baseJobID: Self.jobID, baseGenerationID: "g1",
            snapshot: ["kind": .string("editor"), "editor_payload": .object(["base_generation": .string("g1"), "sections": .object([:])])],
            canUndo: false, createdAt: .now)
        let fake = EditorCommitSpy(draftSnapshot: bootstrap, authoritativeVariant: Self.variant(),
            commitResponse: EditorCommitResponse(ok: true, generation: "g2",
                sections: EditorCommitSections(textElements: true, captionMeta: false, timeline: true, mix: false),
                revisionNumber: 4, revisionHash: "r4", expectedDuration: nil))
        let session = NativeEditorSession()
        await session.load(api: fake, threadID: UUID())
        return (session, fake)
    }

    private func label(_ session: NativeEditorSession, _ n: Int) -> EditorTextElement? {
        session.document.textElements.first { $0.id == "clip-label-unified-cut-\(n)" }
    }

    func testExtendingClip1ShiftsEveryLaterLabelAndOneUndoRestoresBoth() async throws {
        let (session, _) = await loaded()
        XCTAssertEqual(label(session, 1)?.endS, 2)
        let originalText = session.document.textElements
        let originalClips = session.document.clips
        session.setClipTiming(clipID: "s1", durationS: 2.533)
        XCTAssertEqual(label(session, 1)?.startS ?? -1, 0, accuracy: 0.001)
        XCTAssertEqual(label(session, 1)?.endS ?? -1, 2.533, accuracy: 0.001)
        for n in 2...4 {
            XCTAssertEqual(label(session, n)?.startS ?? -1, 2.533 + Double(n - 2) * 2, accuracy: 0.001, "label \(n)")
            XCTAssertEqual(label(session, n)?.endS ?? -1, 2.533 + Double(n - 1) * 2, accuracy: 0.001, "label \(n)")
        }
        XCTAssertTrue(session.dirtySections.contains(.text), "retimed labels must be saved, not just timeline_slots")
        XCTAssertTrue(session.dirtySections.contains(.timeline))
        session.undo()
        XCTAssertEqual(session.document.textElements, originalText)
        XCTAssertEqual(session.document.clips, originalClips)
        XCTAssertFalse(session.canUndo, "a single Undo reverted the clip AND its labels")
        XCTAssertTrue(session.dirtySections.isEmpty)
        session.redo()
        XCTAssertEqual(label(session, 4)?.endS ?? -1, 8.533, accuracy: 0.001)
    }

    func testTrimGestureRipplesLabelsFromTheBaselineWithOneUndoStep() async throws {
        let (session, _) = await loaded()
        let original = session.document.textElements
        let clip = try XCTUnwrap(session.timelineClips.first)
        session.beginTrim(clipID: clip.id, edge: .trailing)
        for translation in [0.2, 0.4, 0.533] { session.updateTrim(by: translation) }
        session.endTrim()
        XCTAssertEqual(label(session, 1)?.endS ?? -1, 2.533, accuracy: 0.001)
        XCTAssertEqual(label(session, 3)?.startS ?? -1, 4.533, accuracy: 0.001, "no cumulative drift across gesture updates")
        session.undo()
        XCTAssertEqual(session.document.textElements, original)
        XCTAssertFalse(session.canUndo)
    }

    func testTrimSelectedFollowsToo() async throws {
        let (session, _) = await loaded()
        let clip = try XCTUnwrap(session.timelineClips.first)
        session.selectClip(clip.id)
        session.trimSelected(edge: .trailing, to: clip.end + 0.533)
        XCTAssertEqual(label(session, 2)?.startS ?? -1, 2.533, accuracy: 0.001)
    }

    func testShorteningKeepsAHandDelayedStartScaled() async throws {
        let (session, _) = await loaded()
        // Creator delayed label 1's start by 0.6s (window 0-2, bar 0.6-1.8).
        var delayed = try XCTUnwrap(label(session, 1))
        delayed.startS = 0.6; delayed.endS = 1.8
        session.transactDocument(section: .text) { doc in
            if let index = doc.textElements.firstIndex(where: { $0.id == delayed.id }) { doc.textElements[index] = delayed }
        }
        session.setClipTiming(clipID: "s1", durationS: 1.0)
        XCTAssertEqual(label(session, 1)?.startS ?? -1, 0.3, accuracy: 0.001)
        XCTAssertEqual(label(session, 1)?.endS ?? -1, 0.9, accuracy: 0.001)
    }

    func testReorderDeleteAndTransitionAllMoveLabels() async throws {
        let (session, _) = await loaded()
        let clip2 = try XCTUnwrap(session.timelineClips.dropFirst().first)
        session.selectClip(clip2.id)
        session.moveSelected(by: 1)
        XCTAssertEqual(label(session, 3)?.startS ?? -1, 2, accuracy: 0.001, "reorder: clip 3 now plays second")
        XCTAssertEqual(label(session, 2)?.startS ?? -1, 4, accuracy: 0.001)

        session.removeClip(clipID: "s1")
        XCTAssertNil(label(session, 1), "a deleted clip's label goes with it")
        XCTAssertEqual(label(session, 3)?.startS ?? -1, 0, accuracy: 0.001)
        XCTAssertEqual(label(session, 4)?.startS ?? -1, 4, accuracy: 0.001)

        session.undo()
        XCTAssertNotNil(label(session, 1), "undo brings the deleted clip's label back")
        XCTAssertEqual(label(session, 3)?.startS ?? -1, 2, accuracy: 0.001)

        session.setClipTransition(clipID: "s1", transition: "crossfade", durationS: 0.3)
        XCTAssertEqual(label(session, 3)?.startS ?? -1, 1.7, accuracy: 0.001, "transition overlap pulls later windows earlier")
    }

    func testDeleteSelectedClipDropsItsLabelAndRipplesTheRest() async throws {
        let (session, _) = await loaded()
        let clip2 = try XCTUnwrap(session.timelineClips.dropFirst().first)
        session.selectClip(clip2.id)
        session.deleteSelectedClip()
        XCTAssertNil(label(session, 2))
        XCTAssertEqual(label(session, 3)?.startS ?? -1, 2, accuracy: 0.001)
        XCTAssertEqual(label(session, 4)?.endS ?? -1, 6, accuracy: 0.001)
        XCTAssertEqual(label(session, 1)?.segmentIDForTest, "s1")
    }

    func testHandEditedTextStyleAndNonLabelBarsSurvive() async throws {
        let (session, _) = await loaded()
        session.setTextStyle(id: "clip-label-unified-cut-2", style: "Inter")
        let styled = try XCTUnwrap(label(session, 2))
        let title = session.document.textElements.first { $0.id == "guided-title" }
        let caption = session.document.textElements.first { $0.id == "caption-1" }
        session.setClipTiming(clipID: "s1", durationS: 2.533)
        let after = try XCTUnwrap(label(session, 2))
        XCTAssertEqual(after.text, styled.text)
        let volatile: Set<String> = ["start_s", "end_s", "segment_id"]
        XCTAssertEqual(after.raw.filter { !volatile.contains($0.key) }, styled.raw.filter { !volatile.contains($0.key) })
        XCTAssertEqual(session.document.textElements.first { $0.id == "guided-title" }, title)
        XCTAssertEqual(session.document.textElements.first { $0.id == "caption-1" }, caption)
    }

    func testEditsThatMoveNoWindowLeaveTextClean() async throws {
        let (session, _) = await loaded()
        session.setClipLookPreset(clipID: "s1", preset: "golden_hour")
        XCTAssertEqual(session.dirtySections, [.timeline])
    }

    func testSavePayloadCarriesRebasedTextElementsWithTimelineSlots() async throws {
        let (session, fake) = await loaded()
        session.setClipTiming(clipID: "s1", durationS: 2.533)
        await session.save()
        let request = try XCTUnwrap(fake.lastRequest)
        XCTAssertNotNil(request.timelineSlots)
        let rows = try XCTUnwrap(request.textElements)
        let second = try XCTUnwrap(rows.compactMap(\.objectValue).first { $0["id"]?.stringValue == "clip-label-unified-cut-2" })
        XCTAssertEqual(second["start_s"]?.numberValue ?? -1, 2.533, accuracy: 0.001)
        XCTAssertEqual(second["segment_id"]?.stringValue, "s2")
    }

    func testTimelineOnlyCommitOnAGuidedStoryStillSendsText() async throws {
        let (session, fake) = await loaded()
        session.setClipLookPreset(clipID: "s1", preset: "golden_hour")
        await session.save()
        let request = try XCTUnwrap(fake.lastRequest)
        XCTAssertNotNil(request.timelineSlots)
        XCTAssertNotNil(request.textElements, "server treats text as authored and skips its label-unaware projection")
    }
}

private extension EditorTextElement { var segmentIDForTest: String? { raw["segment_id"]?.stringValue } }
