import os
import subprocess
import tempfile
import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[3]
IOS_ROOT = REPO_ROOT / "src/apps/ios"
CONFIGURE = REPO_ROOT / "scripts/ios/configure-live-development.sh"


class LiveDevelopmentConfigurationTests(unittest.TestCase):
    def test_project_defines_google_only_live_scheme(self) -> None:
        project = (IOS_ROOT / "project.yml").read_text()
        live = (IOS_ROOT / "Config/LiveDevelopment.xcconfig").read_text()
        development = (IOS_ROOT / "Config/Development.xcconfig").read_text()

        self.assertIn("Live Development: debug", project)
        self.assertIn("Kria Live Development:", project)
        self.assertIn('SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG LIVE_GOOGLE_ONLY"', project)
        self.assertIn('CODE_SIGN_ENTITLEMENTS: ""', project)
        self.assertIn("API_BASE_URL = https:/$()/nova-video.fly.dev", live)
        self.assertIn("600393007296-u2latle2h5ssbms4on8meh4clitc43mt.apps.googleusercontent.com", live)
        self.assertIn(
            "KRIA_PRODUCT_BUNDLE_IDENTIFIER = com.yasin.kria.dev",
            (IOS_ROOT / "Config/Local.xcconfig.example").read_text(),
        )
        self.assertIn("DEBUG DEV_AUTH", development)
        self.assertIn("API_BASE_URL = http:/$()/localhost:8000", development)

    def test_local_setup_writes_only_signing_values(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            output = Path(directory) / "Local.xcconfig"
            env = os.environ | {"KRIA_LOCAL_XCCONFIG_PATH": str(output)}
            result = subprocess.run(
                [str(CONFIGURE), "ABCDE12345", "com.yasin.kria.dev"],
                cwd=REPO_ROOT,
                env=env,
                check=True,
                capture_output=True,
                text=True,
            )

            self.assertIn("Configured Kria Live Development", result.stdout)
            self.assertEqual(
                output.read_text(),
                "// Generated by scripts/ios/configure-live-development.sh. Do not commit.\n"
                "KRIA_DEVELOPMENT_TEAM = ABCDE12345\n"
                "KRIA_PRODUCT_BUNDLE_IDENTIFIER = com.yasin.kria.dev\n",
            )

    def test_local_setup_rejects_invalid_or_existing_configuration(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            output = Path(directory) / "Local.xcconfig"
            env = os.environ | {"KRIA_LOCAL_XCCONFIG_PATH": str(output)}
            invalid = subprocess.run(
                [str(CONFIGURE), "short", "not-a-bundle"],
                cwd=REPO_ROOT,
                env=env,
                capture_output=True,
                text=True,
            )
            self.assertEqual(invalid.returncode, 2)

            wrong_bundle = subprocess.run(
                [str(CONFIGURE), "ABCDE12345", "com.someoneelse.kria.dev"],
                cwd=REPO_ROOT,
                env=env,
                capture_output=True,
                text=True,
            )
            self.assertEqual(wrong_bundle.returncode, 2)
            self.assertIn("match the registered Google iOS OAuth client", wrong_bundle.stderr)

            output.write_text("preserve me\n")
            existing = subprocess.run(
                [str(CONFIGURE), "ABCDE12345", "com.yasin.kria.dev"],
                cwd=REPO_ROOT,
                env=env,
                capture_output=True,
                text=True,
            )
            self.assertEqual(existing.returncode, 2)
            self.assertEqual(output.read_text(), "preserve me\n")


if __name__ == "__main__":
    unittest.main()
