"""Pins `choreography.build_timeline`/`rolling_timeline`'s output against the
checked-in cross-language fixture (`choreography_traces.json`, generated by
`scripts/dev/dump_choreography_fixture.py`).

This is the Python-side half of the choreography parity contract: the TS
suite (`src/apps/web/src/lib/carousel-preview/__tests__/choreography.test.ts`)
asserts its port reproduces the SAME fixture, so this test's job is narrower
— just make sure the Python builders themselves haven't silently drifted
away from what's checked in (which would make the fixture a stale, no-longer-
representative target for the TS side without anything here failing).
"""

from __future__ import annotations

import json
from pathlib import Path

from app.pipeline.carousel.choreography import FocusMoment, build_timeline, rolling_timeline
from app.pipeline.carousel.effects import CardGeometry

FIXTURE_PATH = Path(__file__).parent / "choreography_traces.json"

GEO = CardGeometry(card_w=540, card_h=720, gap=48, corner_radius=24)
VIEWPORT_W = 1080
N_CARDS = 4
SEED = 0


def _round6(x: float) -> float:
    return round(x, 6)


def _dump_frames(frames) -> list[dict]:
    return [
        {
            "t_s": _round6(f.t_s),
            "scroll_x": _round6(f.scroll_x),
            "focus_card": f.focus_card,
            "focus_t": _round6(f.focus_t),
            "dim": _round6(f.dim),
        }
        for f in frames
    ]


def test_fixture_file_exists():
    assert FIXTURE_PATH.exists()


def test_build_timeline_matches_checked_in_fixture():
    fixture = json.loads(FIXTURE_PATH.read_text())
    frames = build_timeline(
        N_CARDS, GEO, VIEWPORT_W, focus_moments=(FocusMoment(card_index=1),), seed=SEED
    )
    assert _dump_frames(frames) == fixture["build_timeline"]["frames"]


def test_rolling_timeline_matches_checked_in_fixture():
    fixture = json.loads(FIXTURE_PATH.read_text())
    frames = rolling_timeline(N_CARDS, GEO, VIEWPORT_W, duration_s=6.0, seed=SEED)
    assert _dump_frames(frames) == fixture["rolling_timeline"]["frames"]
