#!/usr/bin/env bash

set -euo pipefail

usage() {
  cat <<'EOF'
Usage: scripts/ios/configure-live-development.sh [--force] TEAM_ID BUNDLE_ID

Example:
  scripts/ios/configure-live-development.sh ABCDE12345 com.yasin.kria.dev

Find TEAM_ID in Xcode > Settings > Accounts > your Personal Team.
The bundle identifier must be com.yasin.kria.dev because Google's iOS OAuth
client is registered to that exact identifier.
EOF
}

force=false
if [[ "${1:-}" == "--force" ]]; then
  force=true
  shift
fi

[[ $# -eq 2 ]] || { usage >&2; exit 2; }
team_id="$1"
bundle_id="$2"

[[ "$team_id" =~ ^[A-Z0-9]{10}$ ]] || {
  echo "TEAM_ID must be the 10-character identifier shown by Xcode." >&2
  exit 2
}
[[ "$bundle_id" == "com.yasin.kria.dev" ]] || {
  echo "BUNDLE_ID must be com.yasin.kria.dev to match the registered Google iOS OAuth client." >&2
  exit 2
}

repo_root="$(git rev-parse --show-toplevel)"
output_path="${KRIA_LOCAL_XCCONFIG_PATH:-$repo_root/src/apps/ios/Config/Local.xcconfig}"
if [[ -e "$output_path" && "$force" != true ]]; then
  echo "$output_path already exists; use --force to replace it." >&2
  exit 2
fi

mkdir -p "$(dirname "$output_path")"
temporary_path="$(mktemp "${output_path}.XXXXXX")"
trap 'rm -f "$temporary_path"' EXIT
cat >"$temporary_path" <<EOF
// Generated by scripts/ios/configure-live-development.sh. Do not commit.
KRIA_DEVELOPMENT_TEAM = $team_id
KRIA_PRODUCT_BUNDLE_IDENTIFIER = $bundle_id
EOF
mv "$temporary_path" "$output_path"
trap - EXIT

echo "Configured Kria Live Development in $output_path"
echo "Run 'make ios-generate', then select the 'Kria Live Development' scheme in Xcode."
