// Generated by `python -m app.cli.kria_contracts --write`.
// Do not edit by hand; `make verify-kria` checks this file.

export type DeltaEvent = { "id": string; "sequence": number; "revision": number; "role": "user" | "assistant" | "system"; "event_type": string; "content"?: string | null; "payload"?: Record<string, unknown> | null; "created_at": string; };
export type KriaProblem = { "code": string; "phase": "accept" | "plan" | "policy" | "tool" | "approval" | "dispatch" | "observe"; "message": string; "retryable"?: boolean; "recovery"?: "retry" | "refresh_replan" | "ask_user" | "manual" | "none"; "trace_id": string; "current_revision"?: number | null; "target"?: Record<string, string>; };
export type SubmitTurnBody = { "message": string; "client_event_id": string; "expected_thread_revision": number; };
export type TurnAccepted = { "turn_id": string; "thread_revision": number; "status": "pending" | "queued" | "planning" | "executing" | "awaiting_approval" | "observing" | "completed" | "failed" | "cancelled" | "superseded"; "replayed"?: boolean; };
export type TurnCancelBody = { "expected_thread_revision": number; };
export type TurnCancelled = { "turn_id": string; "thread_revision": number; "status": "cancelled"; "approval_ids"?: Array<string>; };
export type ApprovalDecisionBody = { "expected_thread_revision": number; "expected_draft_revision": number; "expected_approval_fingerprint": string; };
export type ApprovalDecisionOut = { "approval_id": string; "turn_id": string; "status": "approved" | "denied"; "thread_revision": number; "render_dispatched"?: false; };
export type ApprovalSnapshotOut = { "approval_id": string; "turn_id": string; "draft_id"?: string | null; "draft_revision"?: number | null; "status": "pending" | "approved" | "denied" | "expired" | "cancelled" | "consumed"; "consequence_summary": string; "cost_summary"?: string | null; "expires_at": string; "approval_fingerprint": string; };
export type DraftSnapshotOut = { "draft_id": string; "item_id": string; "variant_key": string; "draft_revision": number; "snapshot_hash": string; "etag": string; "base_job_id"?: string | null; "base_generation_id"?: string | null; "snapshot": Record<string, unknown>; "can_undo": boolean; "created_at": string; };
export type DraftWriteBody = { "expected_draft_revision": number; "snapshot": Record<string, unknown>; };
export type DraftUndoBody = { "expected_draft_revision": number; };
export type ThreadDeltaOut = { "thread_id": string; "runtime_version": 2; "status": "active" | "archived" | "failed"; "thread_revision": number; "events": Array<DeltaEvent>; "after_sequence": number; "next_after_sequence": number; "before_sequence"?: number | null; "previous_before_sequence"?: number | null; "has_more": boolean; };
export type KriaProblemOut = { "problem": KriaProblem; };

export type KriaApprovalSnapshot = ApprovalSnapshotOut;
export type KriaApprovalDecision = ApprovalDecisionOut;
export type KriaTurnAccepted = TurnAccepted;
export type KriaDelta = ThreadDeltaOut;
export type KriaDraftSnapshot = DraftSnapshotOut;
